'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline/promises');
const puppeteer = require('puppeteer');
const {
    computeRateLimitBackoffMs,
    loadConfig,
    networkCooldownDelay,
    penalizeNetworkScope,
    reserveNetworkSlot,
} = require('./pipeline/core');
const { passwordForEmail } = require('./pipeline/credentials');

const ACCEPT_SELECTOR = '.team_invite .btn_m';
const BASE_DIR = __dirname;
const VERIFIED_ACCOUNTS_PATH = path.join(BASE_DIR, 'completed_accounts.json');
const CONFIRMED_GROUPS_PATH = path.join(BASE_DIR, 'onaylanmis_gruplar.json');
const INVITE_LINK_LOG_PATH = path.join(BASE_DIR, 'grupla.log');

function readPositiveInteger(name, fallback, minimum = 1) {
    const rawValue = process.env[name];
    if (rawValue === undefined || rawValue === '') {
        return fallback;
    }

    const value = Number.parseInt(rawValue, 10);
    if (!Number.isInteger(value) || value <= 0) {
        throw new Error(`${name} pozitif bir tam sayı olmalıdır (gelen: ${rawValue}).`);
    }
    return Math.max(value, minimum);
}

const PIPELINE_DEFAULTS = loadConfig();

const CONFIG = Object.freeze({
    emailPrefix: PIPELINE_DEFAULTS.account.prefix,
    emailDomain: PIPELINE_DEFAULTS.account.domain,
    groupSize: 4,
    loginUrl: 'https://www.oasgames.com/?a=ucenter&m=login',
    eventUrl: 'https://newserver79-lotr.oasgames.com/activity',
    headless: process.env.LEGEND_HEADLESS === 'true',
    navigationTimeoutMs: readPositiveInteger('LEGEND_NAVIGATION_TIMEOUT_MS', 45000),
    actionTimeoutMs: readPositiveInteger('LEGEND_ACTION_TIMEOUT_MS', 30000),
    maxAttempts: readPositiveInteger('LEGEND_MAX_ATTEMPTS', 5),
    retryDelayMs: readPositiveInteger('LEGEND_RETRY_DELAY_MS', 3000),
    verificationAttempts: readPositiveInteger('LEGEND_VERIFY_ATTEMPTS', 5),
    navigationIntervalMs: readPositiveInteger('LEGEND_NAVIGATION_INTERVAL_MS', 15000, 15000),
    accountCooldownMs: readPositiveInteger('LEGEND_ACCOUNT_COOLDOWN_MS', 15000, 15000),
    groupCooldownMs: readPositiveInteger('LEGEND_GROUP_COOLDOWN_MS', 15000, 15000),
    cloudFrontBackoffMs: readPositiveInteger('LEGEND_CLOUDFRONT_BACKOFF_MS', 120000, 120000),
    cloudFrontBackoffMaxMs: readPositiveInteger('LEGEND_CLOUDFRONT_BACKOFF_MAX_MS', 900000, 900000),
    cloudFrontMaxAttempts: readPositiveInteger('LEGEND_CLOUDFRONT_MAX_ATTEMPTS', 3, 3),
    planOnly: process.argv.includes('--plan'),
});

let navigationGate = Promise.resolve();

function sleep(milliseconds) {
    return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

async function waitForNavigationSlot(label, url = CONFIG.eventUrl) {
    const previousGate = navigationGate;
    let releaseGate;
    navigationGate = new Promise((resolve) => {
        releaseGate = resolve;
    });

    await previousGate;
    try {
        const cooldownDelay = await networkCooldownDelay('group');
        if (cooldownDelay > 0) {
            console.log(
                `${label}: BOT 2 403 soğuması için ` +
                `${Math.ceil(cooldownDelay / 1000)} sn bekleniyor...`,
            );
            await sleep(cooldownDelay);
        }
        const globalDelay = await reserveNetworkSlot(url, CONFIG.navigationIntervalMs);
        if (globalDelay > 0) {
            console.log(
                `${label}: ortak CloudFront sırasında ${Math.ceil(globalDelay / 1000)} sn bekleniyor ` +
                `(istekler arası alt sınır ${Math.ceil(CONFIG.navigationIntervalMs / 1000)} sn)...`,
            );
            await sleep(globalDelay);
        }
    } finally {
        releaseGate();
    }
}

function isCloudFrontSignature(status, title, text) {
    const signature = `${title || ''}\n${text || ''}`;
    return status === 403 ||
        /403\s+ERROR/i.test(signature) ||
        /request could not be satisfied/i.test(signature) ||
        /generated by cloudfront/i.test(signature);
}

function cloudFrontInfoFromApiResult(result) {
    const rawText = result && result.rawText ? result.rawText : '';
    const requestIdMatch = rawText.match(/Request ID:\s*([^\s]+)/i);
    return {
        blocked: isCloudFrontSignature(result && result.httpStatus, '', rawText),
        status: result && result.httpStatus,
        title: '',
        text: rawText,
        requestId: requestIdMatch ? requestIdMatch[1] : null,
    };
}

async function cloudFrontPageInfo(page, response) {
    const status = response ? response.status() : null;
    const pageInfo = await page.evaluate(() => {
        const text = String(document.body ? document.body.innerText : '').slice(0, 5000);
        const requestIdMatch = text.match(/Request ID:\s*([^\s]+)/i);
        return {
            title: document.title || '',
            text,
            requestId: requestIdMatch ? requestIdMatch[1] : null,
        };
    }).catch(() => ({ title: '', text: '', requestId: null }));
    const blocked = isCloudFrontSignature(status, pageInfo.title, pageInfo.text);
    return { blocked, status, ...pageInfo };
}

async function waitAfterCloudFrontBlock(attempt, label, info, options = {}) {
    const requestedDelay = computeRateLimitBackoffMs(attempt, {
        baseMs: CONFIG.cloudFrontBackoffMs,
        maximumMs: CONFIG.cloudFrontBackoffMaxMs,
    });
    const delay = await penalizeNetworkScope('legend-global', requestedDelay, undefined, {
        worker: 'group',
        attempt,
        http_status: info.status || null,
    });
    console.warn(
        `${label}: CloudFront 403 algılandı` +
        `${info.requestId ? ` (Request ID=${info.requestId})` : ''}. ` +
        `Aynı oturum korunarak yalnız BOT 2 ${Math.ceil(delay / 1000)} sn bekleyecek.`,
    );
    if (options.sleep !== false) {
        await sleep(delay);
    }
    return delay;
}

async function gotoWithCloudFrontRecovery(page, url, options, label) {
    let lastInfo = null;
    let lastRetryDelayMs = CONFIG.cloudFrontBackoffMs;
    for (let attempt = 1; attempt <= CONFIG.cloudFrontMaxAttempts; attempt += 1) {
        await waitForNavigationSlot(label, url);
        const response = await page.goto(url, options);
        lastInfo = await cloudFrontPageInfo(page, response);
        if (!lastInfo.blocked) {
            return response;
        }
        lastRetryDelayMs = await waitAfterCloudFrontBlock(attempt, label, lastInfo, {
            sleep: attempt < CONFIG.cloudFrontMaxAttempts,
        });
    }

    const error = new Error(
        `${label}: CloudFront 403, ${CONFIG.cloudFrontMaxAttempts} kontrollü denemede açılmadı` +
        `${lastInfo && lastInfo.requestId ? ` (Request ID=${lastInfo.requestId})` : ''}.`,
    );
    error.preventRelogin = true;
    error.cloudFrontBlocked = true;
    error.retryAfterSeconds = Math.ceil(lastRetryDelayMs / 1000);
    throw error;
}

async function reloadWithCloudFrontRecovery(page, options, label) {
    const url = page.url();
    return gotoWithCloudFrontRecovery(page, url, options, label);
}

function emailFor(index) {
    return `${CONFIG.emailPrefix}${index}@${CONFIG.emailDomain}`;
}

function isLeader(index) {
    return (index - 1) % CONFIG.groupSize === 0;
}

function requireValue(value, message) {
    if (value === undefined || value === null || String(value).trim() === '') {
        throw new Error(message);
    }
    return String(value).trim();
}

function parseJson(text) {
    try {
        return JSON.parse(text);
    } catch (_error) {
        return null;
    }
}

function nowIso() {
    return new Date().toISOString();
}

function sha256(value) {
    return crypto.createHash('sha256').update(String(value)).digest('hex');
}

function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function loadVerifiedGroups(verifiedAccountsPath = VERIFIED_ACCOUNTS_PATH) {
    if (!fs.existsSync(verifiedAccountsPath)) {
        throw new Error(`Doğrulanmış hesap dosyası bulunamadı: ${verifiedAccountsPath}`);
    }

    const sourceText = fs.readFileSync(verifiedAccountsPath, 'utf8');
    const source = parseJson(sourceText);
    if (
        !source ||
        source.version !== 1 ||
        !source.completed_accounts ||
        typeof source.completed_accounts !== 'object' ||
        Array.isArray(source.completed_accounts)
    ) {
        throw new Error('completed_accounts.json biçimi geçersiz veya completed_accounts eksik.');
    }

    const emailPattern = new RegExp(
        `^${escapeRegExp(CONFIG.emailPrefix)}(\\d+)@${escapeRegExp(CONFIG.emailDomain)}$`,
        'i',
    );
    const accounts = [];
    const seenIndexes = new Set();

    for (const [rawEmail, details] of Object.entries(source.completed_accounts)) {
        const email = rawEmail.trim().toLowerCase();
        const match = emailPattern.exec(email);
        if (!match) {
            throw new Error(
                `Doğrulanmış hesap e-posta kalıbıyla eşleşmiyor: ${rawEmail}. ` +
                `Beklenen kalıp: ${CONFIG.emailPrefix}<numara>@${CONFIG.emailDomain}`,
            );
        }
        const index = Number.parseInt(match[1], 10);
        if (!Number.isSafeInteger(index) || index <= 0 || seenIndexes.has(index)) {
            throw new Error(`Geçersiz veya tekrarlanan hesap numarası: ${rawEmail}`);
        }
        if (!details || typeof details !== 'object' || !String(details.nickname || '').trim()) {
            throw new Error(`Doğrulanmış hesapta nickname eksik: ${rawEmail}`);
        }

        seenIndexes.add(index);
        accounts.push({
            index,
            email,
            nickname: String(details.nickname).trim(),
            completedAt: String(details.completed_at || ''),
            sourceVerification: details.verification || {},
        });
    }

    accounts.sort((left, right) => left.index - right.index);
    const groupMap = new Map();
    for (const account of accounts) {
        const groupNumber = Math.floor((account.index - 1) / CONFIG.groupSize) + 1;
        const position = ((account.index - 1) % CONFIG.groupSize) + 1;
        const group = groupMap.get(groupNumber) || {
            groupNumber,
            firstIndex: (groupNumber - 1) * CONFIG.groupSize + 1,
            lastIndex: groupNumber * CONFIG.groupSize,
            accounts: [],
        };
        group.accounts.push({ ...account, groupNumber, position });
        groupMap.set(groupNumber, group);
    }

    const allGroups = Array.from(groupMap.values()).sort(
        (left, right) => left.groupNumber - right.groupNumber,
    );
    const completeGroups = [];
    const incompleteGroups = [];
    for (const group of allGroups) {
        group.accounts.sort((left, right) => left.position - right.position);
        const positions = group.accounts.map((account) => account.position);
        const isComplete =
            group.accounts.length === CONFIG.groupSize &&
            positions.every((position, offset) => position === offset + 1);
        (isComplete ? completeGroups : incompleteGroups).push(group);
    }

    if (!completeGroups.length) {
        throw new Error('Gruplandırılabilecek dört üyeli doğrulanmış hesap grubu yok.');
    }

    return {
        accounts,
        completeGroups,
        incompleteGroups,
        sourceHash: sha256(sourceText),
        sourceVersion: source.version,
    };
}

function createAccountRecord(account, previous = null) {
    const baseStatus = account.position === 1 ? 'leader_pending' : 'membership_pending';
    const previousIsCurrent = Boolean(
        previous &&
        previous.email === account.email &&
        previous.nickname_from_verified_accounts === account.nickname,
    );
    return {
        position: account.position,
        group_role: account.position === 1 ? 'leader' : 'member',
        account_index: account.index,
        email: account.email,
        nickname_from_verified_accounts: account.nickname,
        account_creation_verified_at: account.completedAt || null,
        account_creation_verification: account.sourceVerification,
        source_account_verified: true,
        grouping_status: previousIsCurrent
            ? previous.grouping_status
            : baseStatus,
        actual_role_name: previousIsCurrent
            ? previous.actual_role_name || null
            : null,
        grouping_attempt_count: previousIsCurrent
            ? previous.grouping_attempt_count || 0
            : 0,
        last_attempt_at: previousIsCurrent
            ? previous.last_attempt_at || null
            : null,
        confirmed_at: previousIsCurrent
            ? previous.confirmed_at || null
            : null,
        last_error: previousIsCurrent
            ? previous.last_error || null
            : null,
        evidence: previousIsCurrent
            ? previous.evidence || null
            : null,
        attempt_history: previousIsCurrent
            ? previous.attempt_history || []
            : [],
    };
}

function recomputeGroupRecord(groupRecord) {
    const confirmedPositions = groupRecord.accounts
        .filter((account) =>
            account.grouping_status === 'leader_confirmed' ||
            account.grouping_status === 'membership_confirmed',
        )
        .map((account) => account.position)
        .sort((left, right) => left - right);
    const allConfirmed = confirmedPositions.length === CONFIG.groupSize;

    groupRecord.status = allConfirmed
        ? 'confirmed'
        : confirmedPositions.length
            ? 'partially_confirmed'
            : 'pending';
    groupRecord.verification = {
        expected_member_count: CONFIG.groupSize,
        confirmed_member_count: confirmedPositions.length,
        confirmed_positions: confirmedPositions,
        all_members_confirmed: allConfirmed,
        last_server_roster:
            groupRecord.verification && groupRecord.verification.last_server_roster
                ? groupRecord.verification.last_server_roster
                : [],
        last_checked_at:
            groupRecord.verification && groupRecord.verification.last_checked_at
                ? groupRecord.verification.last_checked_at
                : null,
    };
    groupRecord.confirmed_at = allConfirmed
        ? groupRecord.confirmed_at || nowIso()
        : null;
    groupRecord.updated_at = nowIso();
}

function ensureGroupRecord(state, group) {
    const key = String(group.groupNumber);
    const previous = state.groups[key] || null;
    const previousByPosition = new Map(
        previous && Array.isArray(previous.accounts)
            ? previous.accounts.map((account) => [account.position, account])
            : [],
    );
    const groupRecord = {
        group_number: group.groupNumber,
        account_range: {
            first: group.firstIndex,
            last: group.lastIndex,
        },
        leader_position: 1,
        leader_account_index: group.accounts[0].index,
        status: previous ? previous.status : 'pending',
        confirmed_at: previous ? previous.confirmed_at || null : null,
        created_at: previous ? previous.created_at : nowIso(),
        updated_at: nowIso(),
        invite: previous ? previous.invite || null : null,
        verification: previous
            ? previous.verification || null
            : null,
        event_history: previous && Array.isArray(previous.event_history)
            ? previous.event_history
            : [],
        accounts: group.accounts.map((account) =>
            createAccountRecord(account, previousByPosition.get(account.position)),
        ),
    };
    recomputeGroupRecord(groupRecord);
    state.groups[key] = groupRecord;
    return groupRecord;
}

function loadConfirmedGroupState(sourceData, confirmedGroupsPath = CONFIRMED_GROUPS_PATH) {
    let state = null;
    if (fs.existsSync(confirmedGroupsPath)) {
        const text = fs.readFileSync(confirmedGroupsPath, 'utf8');
        state = parseJson(text);
        if (
            !state ||
            state.version !== 1 ||
            state.file_type !== 'legendbots_confirmed_groups' ||
            !state.groups ||
            typeof state.groups !== 'object'
        ) {
            throw new Error(
                `Mevcut onaylanmış grup dosyası bozuk; güvenlik için duruldu: ` +
                `${confirmedGroupsPath}`,
            );
        }
    }

    if (!state) {
        state = {
            version: 1,
            file_type: 'legendbots_confirmed_groups',
            created_at: nowIso(),
            updated_at: nowIso(),
            grouping_policy: {
                group_size: CONFIG.groupSize,
                leader_position: 1,
                rule: 'Hesap numarasına göre her ardışık dört hesap bir grup; en küçük numara lider.',
                membership_positions: [2, 3, 4],
            },
            source: {},
            runs: [],
            groups: {},
        };
    }
    if (!Array.isArray(state.runs)) {
        state.runs = [];
    }
    for (const previousRun of state.runs) {
        if (previousRun.status === 'running') {
            previousRun.status = 'interrupted';
            previousRun.completed_at = nowIso();
            previousRun.error = {
                at: nowIso(),
                message: 'Önceki süreç kesin sonuç yazmadan kapandı; sonraki çalışmada kurtarıldı.',
            };
        }
    }

    state.source = {
        path: path.basename(VERIFIED_ACCOUNTS_PATH),
        sha256: sourceData.sourceHash,
        schema_version: sourceData.sourceVersion,
        verified_account_count: sourceData.accounts.length,
        complete_group_count: sourceData.completeGroups.length,
        incomplete_groups: sourceData.incompleteGroups.map((group) => ({
            group_number: group.groupNumber,
            expected_account_range: [group.firstIndex, group.lastIndex],
            verified_positions: group.accounts.map((account) => account.position),
            verified_emails: group.accounts.map((account) => account.email),
        })),
        last_loaded_at: nowIso(),
    };
    for (const group of sourceData.completeGroups) {
        ensureGroupRecord(state, group);
    }
    state.updated_at = nowIso();
    return state;
}

function persistConfirmedGroupState(state, confirmedGroupsPath = CONFIRMED_GROUPS_PATH) {
    state.updated_at = nowIso();
    const temporaryPath = `${confirmedGroupsPath}.tmp`;
    const content = `${JSON.stringify(state, null, 2)}\n`;
    let descriptor = null;

    try {
        descriptor = fs.openSync(temporaryPath, 'w');
        fs.writeFileSync(descriptor, content, 'utf8');
        fs.fsyncSync(descriptor);
        fs.closeSync(descriptor);
        descriptor = null;
        if (!fs.existsSync(confirmedGroupsPath)) {
            fs.renameSync(temporaryPath, confirmedGroupsPath);
        } else {
            const backupPath = `${confirmedGroupsPath}.bak`;
            fs.rmSync(backupPath, { force: true });
            fs.renameSync(confirmedGroupsPath, backupPath);
            try {
                fs.renameSync(temporaryPath, confirmedGroupsPath);
                try {
                    fs.rmSync(backupPath, { force: true });
                } catch (_backupCleanupError) {
                    // Yeni ana dosya güvenle yerindedir; eski yedek sonraki yazımda temizlenir.
                }
            } catch (replaceError) {
                if (!fs.existsSync(confirmedGroupsPath) && fs.existsSync(backupPath)) {
                    fs.renameSync(backupPath, confirmedGroupsPath);
                }
                throw replaceError;
            }
        }
    } catch (error) {
        if (descriptor !== null) {
            try {
                fs.closeSync(descriptor);
            } catch (_closeError) {
                // Asıl yazma hatası korunur.
            }
        }
        try {
            fs.rmSync(temporaryPath, { force: true });
        } catch (_cleanupError) {
            // Asıl yazma hatası korunur.
        }
        throw new Error(
            `Onaylanmış grup JSON'u atomik yazılamadı (${confirmedGroupsPath}): ` +
            `${error.message}`,
        );
    }
}

function appendGroupEvent(groupRecord, event) {
    groupRecord.event_history.push({ at: nowIso(), ...event });
    if (groupRecord.event_history.length > 200) {
        groupRecord.event_history = groupRecord.event_history.slice(-200);
    }
    groupRecord.updated_at = nowIso();
}

async function promptStartSelection(sourceData) {
    const groupNumbers = sourceData.completeGroups.map((group) => group.groupNumber);
    console.log('\nDoğrulanmış ve gruplandırmaya hazır hesaplar:');
    for (const group of sourceData.completeGroups) {
        console.log(
            `  ${group.groupNumber}. grup: ` +
            group.accounts.map((account) => `${account.position}. üye=${account.email}`).join(' | '),
        );
    }
    if (sourceData.incompleteGroups.length) {
        console.log('\nEksik olduğu için işlenmeyecek gruplar:');
        for (const group of sourceData.incompleteGroups) {
            console.log(
                `  ${group.groupNumber}. grup (${group.firstIndex}-${group.lastIndex}): ` +
                `doğrulanmış konumlar ${group.accounts.map((account) => account.position).join(', ')}`,
            );
        }
    }

    const terminal = readline.createInterface({ input: process.stdin, output: process.stdout });
    const answers = terminal[Symbol.asyncIterator]();
    const ask = async (question) => {
        process.stdout.write(question);
        const answer = await answers.next();
        if (answer.done) {
            throw new Error('Başlangıç seçimi tamamlanmadan giriş akışı kapandı.');
        }
        return answer.value;
    };
    try {
        let groupNumber = null;
        while (!groupNumbers.includes(groupNumber)) {
            const answer = await ask(
                `\nHangi gruptan başlansın? (${groupNumbers.join(', ')}): `,
            );
            groupNumber = Number.parseInt(answer.trim(), 10);
            if (!groupNumbers.includes(groupNumber)) {
                console.log('Lütfen listelenen hazır grup numaralarından birini girin.');
            }
        }

        let memberPosition = null;
        while (![1, 2, 3, 4].includes(memberPosition)) {
            const answer = await ask(
                'O grubun kaçıncı üyesinden başlansın? (1=lider, 2/3/4=üye): ',
            );
            memberPosition = Number.parseInt(answer.trim(), 10);
            if (![1, 2, 3, 4].includes(memberPosition)) {
                console.log('Üye konumu 1, 2, 3 veya 4 olmalıdır.');
            }
        }

        return { groupNumber, memberPosition };
    } finally {
        terminal.close();
    }
}

function buildExecutionPlan(sourceData, selection) {
    const startOffset = sourceData.completeGroups.findIndex(
        (group) => group.groupNumber === selection.groupNumber,
    );
    if (startOffset < 0) {
        throw new Error(`Seçilen ${selection.groupNumber}. grup hazır gruplar arasında yok.`);
    }

    return sourceData.completeGroups.slice(startOffset).map((group, offset) => ({
        group,
        requestedStartPosition: offset === 0 ? selection.memberPosition : 1,
        memberStartPosition: offset === 0
            ? Math.max(2, selection.memberPosition)
            : 2,
    }));
}

function describeApiFailure(result) {
    const body = result.body || {};
    const code = body.err_code || body.code || 'bilinmeyen-kod';
    const message = body.message || body.msg || result.rawText || 'Sunucu ayrıntı vermedi.';
    return `HTTP ${result.httpStatus}, kod=${code}, mesaj=${message}`;
}

async function readEventState(page) {
    return page.evaluate((acceptSelector) => {
        const normalize = (value) => String(value || '').trim();
        const globalValue = (name) => {
            const value = window[name];
            return value === undefined || value === null ? '' : normalize(value);
        };
        const inputValue = (root, selector) => {
            const input = root ? root.querySelector(selector) : null;
            return input ? normalize(input.value) : '';
        };

        const roleElements = Array.from(document.querySelectorAll('.ser_role_list li'));
        const selectedRole =
            document.querySelector('.ser_role_list .ser_role_select') ||
            roleElements[0] ||
            null;
        const roleNameElement = selectedRole ? selectedRole.querySelector('.name') : null;
        const acceptElement = document.querySelector(acceptSelector);

        const teamMembers = Array.from(
            document.querySelectorAll('.event_03_r_t .name_list li'),
        )
            .slice(1)
            .map((item) => {
                const name = item.querySelector('span');
                return name ? normalize(name.textContent) : '';
            })
            .filter((name) => name && name !== '-');
        const visibleAlerts = Array.from(document.querySelectorAll('.alert_page'))
            .filter((element) =>
                element.getClientRects().length &&
                window.getComputedStyle(element).display !== 'none' &&
                window.getComputedStyle(element).visibility !== 'hidden'
            )
            .map((element) => normalize(element.textContent).replace(/\s+/g, ' '))
            .filter(Boolean)
            .slice(0, 5);

        return {
            userId: globalValue('user_id'),
            um: globalValue('um'),
            ud: globalValue('ud'),
            sid: globalValue('sid') || inputValue(selectedRole, '.server_id'),
            roleId: globalValue('roleid') || inputValue(selectedRole, '.role_id'),
            roleName: roleNameElement ? normalize(roleNameElement.textContent) : '',
            serverName: inputValue(selectedRole, '.servername'),
            roleGrade: inputValue(selectedRole, '.role_grade'),
            roleCandidates: roleElements.map((role) => {
                const name = role.querySelector('.name');
                return {
                    sid: inputValue(role, '.server_id'),
                    roleId: inputValue(role, '.role_id'),
                    roleName: name ? normalize(name.textContent) : '',
                    serverName: inputValue(role, '.servername'),
                    roleGrade: inputValue(role, '.role_grade'),
                };
            }),
            teamUid: globalValue('teamud'),
            teamMembers,
            visibleAlerts,
            acceptControl: acceptElement
                ? {
                    found: true,
                    text: normalize(acceptElement.textContent),
                    parentClass: acceptElement.parentElement
                        ? normalize(acceptElement.parentElement.className)
                        : '',
                    visible: Boolean(
                        acceptElement.getClientRects().length &&
                        window.getComputedStyle(acceptElement).visibility !== 'hidden'
                    ),
                }
                : { found: false, text: '', parentClass: '', visible: false },
            loginRequired: Boolean(document.querySelector('.login_in_btn')),
        };
    }, ACCEPT_SELECTOR);
}

async function postFormAndObserve(page, endpoint, fields) {
    const requestUrl = new URL(endpoint, page.url()).href;
    const responsePromise = page.waitForResponse(
        (response) =>
            response.url().split('?')[0] === requestUrl &&
            response.request().method() === 'POST',
        { timeout: CONFIG.actionTimeoutMs },
    );

    const browserFetchPromise = page.evaluate(async ({ path, formFields }) => {
        const body = new URLSearchParams();
        Object.entries(formFields).forEach(([key, value]) => body.set(key, String(value)));

        const response = await fetch(path, {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                'X-Requested-With': 'XMLHttpRequest',
            },
            body: body.toString(),
        });

        return {
            status: response.status,
            text: await response.text(),
        };
    }, { path: endpoint, formFields: fields });

    const [browserResult, observedResponse] = await Promise.all([
        browserFetchPromise,
        responsePromise,
    ]);
    const observedText = await observedResponse.text().catch(() => '');
    const rawText = observedText || browserResult.text || '';

    return {
        httpStatus: observedResponse.status(),
        ok: observedResponse.ok(),
        body: parseJson(rawText),
        rawText: rawText.trim(),
    };
}

async function postFormWithCloudFrontRecovery(page, endpoint, fields, label) {
    let lastResult = null;
    let lastInfo = null;
    let lastRetryDelayMs = CONFIG.cloudFrontBackoffMs;
    for (let attempt = 1; attempt <= CONFIG.cloudFrontMaxAttempts; attempt += 1) {
        await waitForNavigationSlot(label);
        lastResult = await postFormAndObserve(page, endpoint, fields);
        lastInfo = cloudFrontInfoFromApiResult(lastResult);
        if (!lastInfo.blocked) {
            return lastResult;
        }
        lastRetryDelayMs = await waitAfterCloudFrontBlock(attempt, label, lastInfo, {
            sleep: attempt < CONFIG.cloudFrontMaxAttempts,
        });
    }

    const error = new Error(
        `${label}: CloudFront 403, ${CONFIG.cloudFrontMaxAttempts} kontrollü API denemesinde açılmadı` +
        `${lastInfo && lastInfo.requestId ? ` (Request ID=${lastInfo.requestId})` : ''}.`,
    );
    error.preventRelogin = true;
    error.cloudFrontBlocked = true;
    error.retryAfterSeconds = Math.ceil(lastRetryDelayMs / 1000);
    throw error;
}

async function triggerInviteReflow(page) {
    const viewport = await page.evaluate(() => ({
        width: window.innerWidth,
        height: window.innerHeight,
        deviceScaleFactor: window.devicePixelRatio || 1,
    }));
    const compactWidth = Math.max(760, viewport.width - 320);

    await page.setViewport({
        width: compactWidth,
        height: Math.max(640, viewport.height),
        deviceScaleFactor: viewport.deviceScaleFactor,
    });
    await page.evaluate(() => {
        window.dispatchEvent(new Event('resize'));
        if (typeof window.jQuery === 'function') {
            window.jQuery(window).trigger('resize');
        }
    });
    await sleep(300);
    await page.setViewport({
        width: viewport.width,
        height: viewport.height,
        deviceScaleFactor: viewport.deviceScaleFactor,
    });
    await page.evaluate(() => {
        window.dispatchEvent(new Event('resize'));
        if (typeof window.jQuery === 'function') {
            window.jQuery(window).trigger('resize');
        }
    });
    await sleep(300);
}

async function isAcceptVisible(page) {
    return page
        .$eval(
            ACCEPT_SELECTOR,
            (element) => Boolean(
                element.getClientRects().length &&
                window.getComputedStyle(element).visibility !== 'hidden' &&
                window.getComputedStyle(element).display !== 'none'
            ),
        )
        .catch(() => false);
}

async function clickAcceptWithMouseAndObserve(page, expectedFields) {
    const requestUrl = new URL('/agreeTeam', page.url()).href;
    let observedResponse = null;
    let responseFailure = null;
    const responsePromise = page.waitForResponse(
        (response) =>
            response.url().split('?')[0] === requestUrl &&
            response.request().method() === 'POST',
        { timeout: CONFIG.actionTimeoutMs },
    ).then((response) => {
        observedResponse = response;
        return response;
    }).catch((error) => {
        responseFailure = error;
        return null;
    });
    await page.evaluate(({ selector, fields }) => {
        const previous = window.__legendControlledJoin;
        if (previous && previous.handler) {
            document.removeEventListener('click', previous.handler, true);
        }

        const state = {
            pending: false,
            result: null,
            handler: null,
        };
        state.handler = async (event) => {
            const clickedAccept = event.target instanceof Element
                ? event.target.closest(selector)
                : null;
            const target = event.target instanceof Element
                ? event.target.closest('.team_invite')
                : null;
            if (!target || !clickedAccept || state.pending || state.result) {
                return;
            }

            event.preventDefault();
            event.stopPropagation();
            event.stopImmediatePropagation();
            state.pending = true;
            try {
                const body = new URLSearchParams();
                Object.entries(fields).forEach(([key, value]) => body.set(key, String(value)));
                const response = await fetch('/agreeTeam', {
                    method: 'POST',
                    credentials: 'same-origin',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                        'X-Requested-With': 'XMLHttpRequest',
                    },
                    body: body.toString(),
                });
                state.result = {
                    status: response.status,
                    statusText: response.statusText,
                    contentType: response.headers.get('content-type'),
                    ok: response.ok,
                    text: await response.text(),
                };
            } catch (error) {
                state.result = {
                    status: 0,
                    statusText: '',
                    contentType: null,
                    ok: false,
                    text: '',
                    fetchError: error && error.message ? error.message : String(error),
                };
            } finally {
                state.pending = false;
            }
        };
        window.__legendControlledJoin = state;
        document.addEventListener('click', state.handler, true);
    }, { selector: ACCEPT_SELECTOR, fields: expectedFields });

    let clickCount = 0;
    for (let attempt = 1; attempt <= 5; attempt += 1) {
        await page.bringToFront();
        await triggerInviteReflow(page);

        const acceptButton = await page.$(ACCEPT_SELECTOR);
        if (!acceptButton) {
            if (observedResponse || !(await isAcceptVisible(page))) {
                break;
            }
            throw new Error('Görünür "Kabul Et" alanı mouse tıklaması için bulunamadı.');
        }
        await acceptButton.scrollIntoView();
        const box = await acceptButton.boundingBox();
        if (!box || box.width <= 0 || box.height <= 0) {
            await sleep(350);
            continue;
        }

        const x = box.x + box.width / 2;
        const y = box.y + box.height / 2;
        await page.mouse.move(x, y, { steps: 8 });
        await page.mouse.down({ button: 'left' });
        await sleep(90);
        await page.mouse.up({ button: 'left' });
        clickCount += 1;

        await Promise.race([responsePromise, sleep(900)]);
        const requestCompleted = await page.evaluate(() => Boolean(
            window.__legendControlledJoin && window.__legendControlledJoin.result
        ));
        if (observedResponse || requestCompleted) {
            break;
        }
    }

    if (!clickCount) {
        throw new Error('"Kabul Et" alanına gerçek mouse olayı gönderilemedi.');
    }

    if (!observedResponse) {
        await responsePromise;
    }

    await page.waitForFunction(
        () => Boolean(window.__legendControlledJoin && window.__legendControlledJoin.result),
        { timeout: CONFIG.actionTimeoutMs },
    );
    const pageResult = await page.evaluate(() => {
        const state = window.__legendControlledJoin;
        if (!state || !state.result) {
            return null;
        }
        document.removeEventListener('click', state.handler, true);
        return state.result;
    });
    if (!pageResult) {
        throw new Error('Kontrollü mouse tıklamasının sayfa içi yanıtı alınamadı.');
    }
    if (!observedResponse) {
        throw new Error(
            `Mouse tıklaması sonrasında /agreeTeam isteği gözlenmedi: ` +
            `${responseFailure ? responseFailure.message : 'zaman aşımı'}`,
        );
    }
    const postedData = new URLSearchParams(observedResponse.request().postData() || '');
    for (const [key, expectedValue] of Object.entries(expectedFields)) {
        if (postedData.get(key) !== String(expectedValue)) {
            throw new Error(
                `/agreeTeam isteğinin ${key} alanı beklenen değerle eşleşmedi.`,
            );
        }
    }

    const observedText = await observedResponse.text().catch(() => '');
    const rawText = pageResult.text || observedText || '';
    const result = {
        httpStatus: pageResult.status || observedResponse.status(),
        httpStatusText: pageResult.statusText || observedResponse.statusText(),
        contentType:
            pageResult.contentType || observedResponse.headers()['content-type'] || null,
        ok: pageResult.ok && observedResponse.ok(),
        body: parseJson(rawText),
        rawText: rawText.trim(),
        invitationDismissedImmediately: false,
        controlledPanelKeptOpenUntilResponse: await isAcceptVisible(page),
        physicalMouseClickCount: clickCount,
        navigatedAfterSuccess: false,
        fetchError: pageResult.fetchError || null,
    };
    return result;
}

async function login(page, email, cloudFrontAttempt = 1) {
    console.log(`[${email}] OAS hesabına giriş yapılıyor...`);
    await gotoWithCloudFrontRecovery(page, CONFIG.loginUrl, {
        waitUntil: 'domcontentloaded',
        timeout: CONFIG.navigationTimeoutMs,
    }, `[${email}] giriş sayfası`);
    await page.waitForSelector('#user_email', { visible: true });
    await page.waitForSelector('#fake_pass_01', { visible: true });
    await page.waitForSelector('.login_btn', { visible: true });

    // Giriş bilgileri DOM'a doğrudan yazılmaz. Gerçek gizli pencere üzerinde
    // alanlara tıklanır ve klavye olaylarıyla, kullanıcı gibi yazılır.
    await page.click('#user_email');
    await page.type('#user_email', email, { delay: 55 });
    await page.click('#fake_pass_01');
    await page.waitForSelector('#user_password', { visible: true });
    await page.click('#user_password');
    await page.type('#user_password', passwordForEmail(email), { delay: 70 });

    await waitForNavigationSlot(`[${email}] giriş gönderimi`, CONFIG.loginUrl);
    const navigationPromise = page
        .waitForNavigation({
            waitUntil: 'networkidle2',
            timeout: CONFIG.navigationTimeoutMs,
        })
        .catch(() => null);
    await page.click('.login_btn');

    const deadline = Date.now() + CONFIG.navigationTimeoutMs;
    let loginCookie = null;
    let detectedCloudFrontInfo = null;
    let nextCloudFrontScanAt = 0;
    while (Date.now() < deadline) {
        const cookies = await page.cookies().catch(() => []);
        loginCookie = cookies.find(
            (cookie) => cookie.name === 'oas_user' && cookie.value,
        );
        if (loginCookie) {
            break;
        }
        if (Date.now() >= nextCloudFrontScanAt) {
            detectedCloudFrontInfo = await cloudFrontPageInfo(page, null);
            if (detectedCloudFrontInfo.blocked) {
                break;
            }
            nextCloudFrontScanAt = Date.now() + 1000;
        }
        await sleep(300);
    }

    if (!loginCookie) {
        const cloudFrontInfo = detectedCloudFrontInfo && detectedCloudFrontInfo.blocked
            ? detectedCloudFrontInfo
            : await cloudFrontPageInfo(page, null);
        if (cloudFrontInfo.blocked && cloudFrontAttempt < CONFIG.cloudFrontMaxAttempts) {
            await waitAfterCloudFrontBlock(
                cloudFrontAttempt,
                `[${email}] giriş yanıtı`,
                cloudFrontInfo,
            );
            return login(page, email, cloudFrontAttempt + 1);
        }
        if (cloudFrontInfo.blocked) {
            const retryDelayMs = await waitAfterCloudFrontBlock(
                cloudFrontAttempt,
                `[${email}] giriş yanıtı`,
                cloudFrontInfo,
                { sleep: false },
            );
            const error = new Error(
                `[${email}] giriş yanıtı CloudFront 403 nedeniyle ` +
                `${CONFIG.cloudFrontMaxAttempts} kontrollü denemede tamamlanamadı` +
                `${cloudFrontInfo.requestId ? ` (Request ID=${cloudFrontInfo.requestId})` : ''}.`,
            );
            error.preventRelogin = true;
            error.cloudFrontBlocked = true;
            error.retryAfterSeconds = Math.ceil(retryDelayMs / 1000);
            throw error;
        }
        const visibleErrors = await page
            .evaluate(() =>
                Array.from(document.querySelectorAll('[class*="error"], [class*="tip"]'))
                    .filter((element) => element.getClientRects().length)
                    .map((element) => String(element.textContent || '').trim())
                    .filter(Boolean)
                    .slice(0, 5),
            )
            .catch(() => []);
        throw new Error(
            `Gerçek giriş düğmesine basıldı ancak oas_user oturumu oluşmadı` +
            `${visibleErrors.length ? `: ${visibleErrors.join(' | ')}` : '.'}`,
        );
    }

    const completedNavigation = await navigationPromise;
    if (!completedNavigation) {
        await page
            .waitForNetworkIdle({ idleTime: 750, timeout: CONFIG.actionTimeoutMs })
            .catch(() => {});
    }
    console.log(`[${email}] Giriş oturumu doğrulandı.`);
}

async function openEventPage(page, url = CONFIG.eventUrl) {
    await gotoWithCloudFrontRecovery(page, url, {
        waitUntil: 'networkidle2',
        timeout: CONFIG.navigationTimeoutMs,
    }, 'Etkinlik sayfası');
    await page.waitForFunction(
        () => typeof window.user_id !== 'undefined' && typeof window.um !== 'undefined',
        { timeout: CONFIG.actionTimeoutMs },
    );

    const state = await readEventState(page);
    requireValue(state.userId, 'Etkinlik sayfasında user_id bulunamadı; oturum doğrulanamadı.');
    requireValue(state.um, 'Etkinlik sayfasında um bulunamadı; oturum doğrulanamadı.');
    return state;
}

async function ensureLeaderLinkReady(page, initialState, expectedNickname) {
    const expectedRoleName = requireValue(
        expectedNickname,
        'Doğrulanmış hesap kaydında beklenen nickname bulunamadı.',
    );
    if (
        initialState.sid &&
        initialState.ud &&
        initialState.userId &&
        initialState.um
    ) {
        return {
            ...initialState,
            roleName: initialState.roleName || expectedRoleName,
            roleNameSource: initialState.roleName
                ? 'event_dom'
                : 'completed_accounts.json',
        };
    }

    const roleCandidates = initialState.roleCandidates || [];
    const roleToBind =
        roleCandidates.find((role) => role.roleName === expectedRoleName) ||
        roleCandidates[0] ||
        null;
    if (!roleToBind) {
        throw new Error(
            `Lider linki için window.sid/window.ud eksik ve bağlanabilecek rol listesi yok.`,
        );
    }

    const roleFields = {
        user_id: requireValue(initialState.userId, 'Rol bağlama için user_id bulunamadı.'),
        sid: requireValue(roleToBind.sid, 'Bağlanabilecek sunucu rolü bulunamadı (sid eksik).'),
        role_id: requireValue(
            roleToBind.roleId,
            'Bağlanabilecek sunucu rolü bulunamadı (role_id eksik).',
        ),
        um: requireValue(initialState.um, 'Rol bağlama için um bulunamadı.'),
        server_name: requireValue(
            roleToBind.serverName,
            'Bağlanabilecek rolün sunucu adı bulunamadı.',
        ),
        role_name: requireValue(roleToBind.roleName, 'Bağlanabilecek rolün adı bulunamadı.'),
        role_grade: requireValue(
            roleToBind.roleGrade,
            'Bağlanabilecek rolün seviyesi bulunamadı.',
        ),
    };

    console.log(`Rol etkinliğe bağlanıyor: ${roleFields.role_name}`);
    const result = await postFormWithCloudFrontRecovery(
        page,
        '/binding',
        roleFields,
        `Lider rol bağlama isteği`,
    );
    if (!result.ok || !result.body || result.body.status !== 'success') {
        throw new Error(`Rol bağlama isteği başarısız: ${describeApiFailure(result)}`);
    }

    await reloadWithCloudFrontRecovery(page, {
        waitUntil: 'domcontentloaded',
        timeout: CONFIG.navigationTimeoutMs,
    }, 'Lider rol bağlama doğrulaması');
    const verifiedState = await readEventState(page);
    requireValue(verifiedState.sid, 'Rol bağlama sonrası sid doğrulanamadı.');
    requireValue(verifiedState.ud, 'Rol bağlama sonrası ud doğrulanamadı.');
    console.log(`Rol bağlama sonrası lider link verileri sunucudan doğrulandı.`);
    return {
        ...verifiedState,
        roleName: verifiedState.roleName || roleToBind.roleName || expectedRoleName,
        roleNameSource: verifiedState.roleName ? 'event_dom' : 'binding_or_completed_accounts',
    };
}

async function readLeaderLinkData(page) {
    const linkData = await page.evaluate(() => {
        const sid = window.sid || null;
        const ud = window.ud || null;
        const user_id = window.user_id || null;
        const um = window.um || null;

        if (!sid || !ud || !user_id || !um) {
            return null;
        }
        return { sid, ud, user_id, um };
    });

    if (!linkData) {
        throw new Error('Lider sayfasında sid, ud, user_id veya um bulunamadı.');
    }
    return linkData;
}

function buildLeaderLink(linkData) {
    const type = 'team';
    const baseLink = CONFIG.eventUrl;
    return `${baseLink}?sid=${linkData.sid}&ud=${linkData.ud}` +
        `&type=${type}&shareuid=${linkData.user_id}&um=${linkData.um}`;
}

function logLeaderInviteLink(account, roleName, leaderLink, targetPath = INVITE_LINK_LOG_PATH) {
    const entry = {
        timestamp: nowIso(),
        event: 'leader_invite_link_created',
        group_number: account.groupNumber,
        leader_account_index: account.index,
        leader_email: account.email,
        leader_role_name: roleName,
        invite_url: leaderLink,
    };
    fs.appendFileSync(targetPath, `${JSON.stringify(entry)}\n`, {
        encoding: 'utf8',
        mode: 0o600,
    });
    console.log(`[${account.email}] TAM DAVET LİNKİ: ${leaderLink}`);
    console.log(`[${account.email}] Davet linki günlüğe yazıldı: ${targetPath}`);
}

async function createLeaderContext(page, account) {
    const { email, index } = account;
    let state = await openEventPage(page);
    state = await ensureLeaderLinkReady(page, state, account.nickname);

    if (state.roleName && state.roleNameSource === 'event_dom' && state.roleName !== account.nickname) {
        throw new Error(
            `Lider rolü doğrulanmış hesapla eşleşmiyor. ` +
            `Beklenen=${account.nickname}, görünen=${state.roleName}.`,
        );
    }
    const roleName = account.nickname;
    const linkData = await readLeaderLinkData(page);
    const leaderLink = buildLeaderLink(linkData);
    const knownMembers = new Set(state.teamMembers);
    knownMembers.add(roleName);

    console.log(`[${email}] Takım lideri doğrulandı: ${roleName}`);
    logLeaderInviteLink(account, roleName, leaderLink);
    console.log(
        `[${email}] Takım davet linki oluşturuldu ` +
        `(güvenli iz=${sha256(leaderLink).slice(0, 16)}…).`,
    );
    return {
        index,
        email,
        roleName,
        roleNameSource: state.roleNameSource || 'completed_accounts.json',
        link: leaderLink,
        serverId: String(linkData.sid),
        roleId: state.roleId || null,
        initialRoster: state.teamMembers,
        knownMembers,
    };
}

function normalizedRoleName(value) {
    return String(value || '').trim().toLowerCase();
}

function rosterRole(roster, expectedRoleName) {
    const expected = normalizedRoleName(expectedRoleName);
    return roster.find((name) => normalizedRoleName(name) === expected) || null;
}

function membershipMatches(state, roleName, leaderContext) {
    return (
        Boolean(rosterRole(state.teamMembers, roleName)) &&
        Boolean(rosterRole(state.teamMembers, leaderContext.roleName))
    );
}

function reconcileGroupAccountsFromRoster(groupRecord, roster, runId) {
    const reconciledPositions = [];
    for (const accountRecord of groupRecord.accounts) {
        const actualRoleName = rosterRole(
            roster,
            accountRecord.nickname_from_verified_accounts,
        );
        if (!actualRoleName) {
            continue;
        }

        const alreadyConfirmed =
            accountRecord.grouping_status === 'leader_confirmed' ||
            accountRecord.grouping_status === 'membership_confirmed';
        if (!alreadyConfirmed) {
            accountRecord.grouping_status = accountRecord.position === 1
                ? 'leader_confirmed'
                : 'membership_confirmed';
            accountRecord.confirmed_at = nowIso();
            accountRecord.last_error = null;
            accountRecord.evidence = {
                run_id: runId,
                join_mode: 'server_roster_reconciliation',
                source: 'Küçük Takımın sunucu kadrosu',
                roster,
                expected_role_name: accountRecord.nickname_from_verified_accounts,
                actual_role_name: actualRoleName,
                case_insensitive_match: true,
            };
            reconciledPositions.push(accountRecord.position);
        }
        accountRecord.actual_role_name = actualRoleName;
    }

    if (reconciledPositions.length) {
        appendGroupEvent(groupRecord, {
            run_id: runId,
            type: 'accounts_reconciled_from_server_roster',
            positions: reconciledPositions,
            roster,
        });
    }
}

async function verifyMembership(page, roleName, leaderContext) {
    let lastState = null;

    for (let attempt = 1; attempt <= CONFIG.verificationAttempts; attempt += 1) {
        if (attempt === 1) {
            lastState = await openEventPage(page);
        } else {
            await sleep(Math.min(attempt * 750, 2500));
            await reloadWithCloudFrontRecovery(page, {
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.navigationTimeoutMs,
            }, 'Takım üyeliği doğrulaması');
            lastState = await readEventState(page);
        }

        if (membershipMatches(lastState, roleName, leaderContext)) {
            return lastState;
        }

        console.log(
            `Takım listesi henüz güncellenmedi (${attempt}/${CONFIG.verificationAttempts}); ` +
            `görünen üyeler: ${lastState.teamMembers.join(', ') || 'yok'}`,
        );
    }

    throw new Error(
        `Sunucu takım listesi üyeliği doğrulamadı. Beklenen lider=${leaderContext.roleName}, ` +
        `beklenen üye=${roleName}, görünen=${lastState.teamMembers.join(', ') || 'yok'}.`,
    );
}

async function verifyInvitationClosedTwice(page, roleName, leaderContext) {
    let lastState = null;

    for (let check = 1; check <= 2; check += 1) {
        if (check === 1) {
            lastState = await openEventPage(page, leaderContext.link);
        } else {
            await reloadWithCloudFrontRecovery(page, {
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.navigationTimeoutMs,
            }, `Davet ekranı kalıcılık kontrolü ${check}/2`);
            lastState = await readEventState(page);
        }

        if (!membershipMatches(lastState, roleName, leaderContext)) {
            throw new Error(
                `Davet ekranı kontrolü ${check}/2 sırasında takım üyeliği kayboldu. ` +
                `Görünen üyeler: ${lastState.teamMembers.join(', ') || 'yok'}.`,
            );
        }
        if (lastState.acceptControl.visible) {
            throw new Error(
                `Davet ekranı kontrolü ${check}/2 başarısız: "Kabul Et" hâlâ görünür.`,
            );
        }

        console.log(
            `Davet ekranı kalıcılık kontrolü ${check}/2 başarılı: ` +
            `"Kabul Et" kapalı ve takım üyeliği korunuyor.`,
        );
    }

    return lastState;
}

async function inspectMembershipWithoutLeavingInvite(page, roleName, leaderContext) {
    const verificationPage = await page.browserContext().newPage();
    configureAutomationPage(verificationPage);
    await page.bringToFront();
    let lastState = null;

    try {
        const checks = Math.min(2, CONFIG.verificationAttempts);
        for (let attempt = 1; attempt <= checks; attempt += 1) {
            try {
                if (attempt === 1) {
                    lastState = await openEventPage(verificationPage);
                } else {
                    await sleep(900);
                    await reloadWithCloudFrontRecovery(verificationPage, {
                        waitUntil: 'networkidle2',
                        timeout: CONFIG.navigationTimeoutMs,
                    }, `Arka plan takım doğrulaması ${attempt}/${checks}`);
                    lastState = await readEventState(verificationPage);
                }
            } catch (verificationError) {
                if (verificationError.cloudFrontBlocked) {
                    throw verificationError;
                }
                lastState = null;
            }
            if (lastState && membershipMatches(lastState, roleName, leaderContext)) {
                return lastState;
            }
        }
        return null;
    } finally {
        await verificationPage.close().catch(() => {});
        await page.bringToFront().catch(() => {});
    }
}

async function closeInvitePanelAfterServerVerification(page) {
    await page.evaluate((selector) => {
        const accept = document.querySelector(selector);
        const panel = accept ? accept.closest('.alert_page') : null;
        if (panel) {
            panel.style.display = 'none';
        }
    }, ACCEPT_SELECTOR);
    return !(await isAcceptVisible(page));
}

function selectMemberRegistrationRole(roleCandidates, serverId, nickname) {
    const serverRoles = (roleCandidates || []).filter(
        (role) => String(role.sid) === String(serverId),
    );
    const normalizedNickname = normalizedRoleName(nickname);
    const exact = serverRoles.find(
        (role) => normalizedRoleName(role.roleName) === normalizedNickname,
    );
    if (exact) {
        return exact;
    }
    if (/^(existing[ _-]?account|mevcut[ _-]?hesap)$/i.test(String(nickname || '').trim())) {
        return serverRoles.find((role) => {
            const value = normalizedRoleName(role.roleName);
            return value && value !== 'boş' && value !== 'bos' && value !== 'empty';
        }) || null;
    }
    return null;
}

async function ensureMemberEventRegistration(page, initialState, account, leaderContext) {
    if (initialState.ud) {
        return {
            ...initialState,
            memberEventRegistration: {
                required: false,
                verified: true,
                reason: 'Etkinlik kullanıcı kaydı zaten mevcut.',
            },
        };
    }

    const matchingRole = selectMemberRegistrationRole(
        initialState.roleCandidates,
        leaderContext.serverId,
        account.nickname,
    );
    if (!matchingRole) {
        throw new Error(
            `Üye etkinlik kaydı için uygun rol bulunamadı. ` +
            `Beklenen sunucu=${leaderContext.serverId}, rol=${account.nickname}; adaylar=` +
            `${(initialState.roleCandidates || [])
                .map((role) => `${role.sid}:${role.roleName}`)
                .join(', ') || 'yok'}.`,
        );
    }

    console.log(
        `[${account.email}] Etkinlik kullanıcı kaydı eksik; ` +
        `${matchingRole.sid}:${matchingRole.roleName} rolü bağlanıyor...`,
    );
    const result = await postFormWithCloudFrontRecovery(page, '/binding', {
        user_id: requireValue(initialState.userId, 'Üye bağlama için user_id bulunamadı.'),
        sid: requireValue(matchingRole.sid, 'Üye bağlama için sid bulunamadı.'),
        role_id: requireValue(matchingRole.roleId, 'Üye bağlama için role_id bulunamadı.'),
        um: requireValue(initialState.um, 'Üye bağlama için um bulunamadı.'),
        server_name: requireValue(
            matchingRole.serverName,
            'Üye bağlama için sunucu adı bulunamadı.',
        ),
        role_name: requireValue(matchingRole.roleName, 'Üye bağlama için rol adı bulunamadı.'),
        role_grade: requireValue(
            matchingRole.roleGrade,
            'Üye bağlama için rol seviyesi bulunamadı.',
        ),
    }, `[${account.email}] üye rol bağlama isteği`);
    if (!result.ok || !result.body || result.body.status !== 'success') {
        throw new Error(
            `Üye etkinlik kaydı oluşturulamadı: ${describeApiFailure(result)}`,
        );
    }

    await reloadWithCloudFrontRecovery(page, {
        waitUntil: 'networkidle2',
        timeout: CONFIG.navigationTimeoutMs,
    }, `[${account.email}] üye rol bağlama doğrulaması`);
    const registeredState = await readEventState(page);
    requireValue(registeredState.ud, 'Üye bağlama sonrası ud oluşmadı.');
    requireValue(registeredState.userId, 'Üye bağlama sonrası user_id kayboldu.');
    requireValue(registeredState.um, 'Üye bağlama sonrası um kayboldu.');
    console.log(`[${account.email}] Etkinlik kullanıcı kaydı sunucudan doğrulandı.`);
    return {
        ...registeredState,
        memberEventRegistration: {
            required: true,
            verified: true,
            endpoint: '/binding',
            server_id: String(matchingRole.sid),
            role_id: String(matchingRole.roleId),
            role_name: matchingRole.roleName,
            http_status: result.httpStatus,
            response_status: result.body.status,
        },
    };
}

async function joinLeaderTeam(page, account, leaderContext) {
    const { email } = account;
    console.log(
        `[${email}] Bellekteki lider linki ikinci gizli sekmede açılıyor ` +
        `(iz=${sha256(leaderContext.link).slice(0, 16)}…).`,
    );
    let state = await openEventPage(page, leaderContext.link);
    state = await ensureMemberEventRegistration(
        page,
        state,
        account,
        leaderContext,
    );

    const placeholderNickname = /^(existing[ _-]?account|mevcut[ _-]?hesap)$/i.test(
        String(account.nickname || '').trim(),
    );
    const recoveredRoleName = state.roleName ||
        (state.memberEventRegistration && state.memberEventRegistration.role_name) || '';
    if (state.roleName && !placeholderNickname && state.roleName !== account.nickname) {
        throw new Error(
            `Katılımcı rolü doğrulanmış hesapla eşleşmiyor. ` +
            `Beklenen=${account.nickname}, görünen=${state.roleName}.`,
        );
    }
    if (placeholderNickname && !recoveredRoleName) {
        throw new Error(
            `Yer tutucu hesap kaydı için gerçek rol adı etkinlik sunucusundan çözülemedi.`,
        );
    }
    const roleName = placeholderNickname ? recoveredRoleName : account.nickname;
    const roleNameSource = placeholderNickname
        ? 'event_dom_placeholder_recovery'
        : state.roleName ? 'event_dom' : 'completed_accounts.json';
    if (membershipMatches(state, roleName, leaderContext)) {
        console.log(
            `[${email}] ${roleName} zaten doğru takımda; sunucu listesinden idempotent doğrulandı.`,
        );
        const persistentState = await verifyInvitationClosedTwice(
            page,
            roleName,
            leaderContext,
        );
        leaderContext.knownMembers.add(roleName);
        return {
            roleName,
            state: persistentState,
            alreadyMember: true,
            evidence: {
                join_mode: 'already_in_expected_team',
                role_name_source: roleNameSource,
                event_registration: state.memberEventRegistration,
                api: {
                    request_sent: false,
                    reason: 'Sunucu listesi üyeliği işlem öncesinde doğruladı.',
                },
                server: {
                    expected_leader_role: leaderContext.roleName,
                    expected_member_role: roleName,
                    roster: persistentState.teamMembers,
                    membership_match: true,
                },
                invitation_ui: {
                    dismissed_immediately: true,
                    persistent_closed_checks: 2,
                    persistent_closed: true,
                },
            },
        };
    }

    if (!state.acceptControl.found || state.acceptControl.text !== 'Kabul Et') {
        throw new Error('Görünür davet panelinde "Kabul Et" öğesi bulunamadı.');
    }
    if (!state.acceptControl.parentClass.split(/\s+/).includes('team_invite')) {
        throw new Error(
            `"Kabul Et" öğesi beklenen .team_invite tıklama alanının içinde değil: ` +
            `${state.acceptControl.parentClass || 'sınıf yok'}`,
        );
    }
    if (!state.acceptControl.visible) {
        const verifiedHiddenState = await inspectMembershipWithoutLeavingInvite(
            page,
            roleName,
            leaderContext,
        );
        if (verifiedHiddenState) {
            const persistentState = await verifyInvitationClosedTwice(
                page,
                roleName,
                leaderContext,
            );
            leaderContext.knownMembers.add(roleName);
            return {
                roleName,
                state: persistentState,
                alreadyMember: true,
                evidence: {
                    join_mode: 'hidden_invite_but_expected_team_verified',
                    role_name_source: roleNameSource,
                    event_registration: state.memberEventRegistration,
                    api: {
                        request_sent: false,
                        reason: 'Davet paneli zaten kapalıydı; üyelik sunucu kadrosundan doğrulandı.',
                    },
                    server: {
                        expected_leader_role: leaderContext.roleName,
                        expected_member_role: roleName,
                        roster: persistentState.teamMembers,
                        membership_match: true,
                    },
                    invitation_ui: {
                        dismissed_immediately: false,
                        already_closed_on_load: true,
                        persistent_closed_checks: 2,
                        persistent_closed: true,
                    },
                },
            };
        }

        const error = new Error(
            `"Kabul Et" paneli görünür değil ve beklenen takım doğrulanamadı. ` +
            `Görünen kadro=${state.teamMembers.join(', ') || 'yok'}; ` +
            `uyarılar=${state.visibleAlerts.join(' | ') || 'yok'}.`,
        );
        error.preventRelogin = true;
        throw error;
    }

    await page.waitForFunction(
        () =>
            typeof window.jQuery === 'function' &&
            window.LO &&
            typeof window.LO.agreeTeam === 'function',
        { timeout: CONFIG.actionTimeoutMs },
    );
    console.log(`[${email}] Davet ekranı hazır; ilk tıklamadan önce 3 saniye bekleniyor...`);
    await sleep(3000);

    const requestFields = {
        user_id: requireValue(state.userId, '/agreeTeam için user_id bulunamadı.'),
        um: requireValue(state.um, '/agreeTeam için um bulunamadı.'),
        teamuid: requireValue(state.teamUid, '/agreeTeam için teamud bulunamadı.'),
    };

    let result = null;
    let responseStatus = null;
    let errorCode = null;
    let verifiedState = null;
    let recoveredFromNonSuccessResponse = false;
    let controlledRequestAttempt = 0;
    let cloudFrontRecoveryCount = 0;

    for (let attempt = 1; attempt <= CONFIG.maxAttempts; attempt += 1) {
        controlledRequestAttempt = attempt;
        await waitForNavigationSlot(`[${email}] /agreeTeam isteği`);
        console.log(
            `[${email}] Davet paneli açık tutularak gerçek mouse tıklaması yapılıyor ` +
            `(${attempt}/${CONFIG.maxAttempts})...`,
        );
        result = await clickAcceptWithMouseAndObserve(page, requestFields);
        responseStatus = result.body && result.body.status;
        errorCode = result.body && result.body.err_code;
        const cloudFrontInfo = cloudFrontInfoFromApiResult(result);
        if (cloudFrontInfo.blocked) {
            cloudFrontRecoveryCount += 1;
            if (attempt >= CONFIG.maxAttempts) {
                const retryDelayMs = await waitAfterCloudFrontBlock(
                    cloudFrontRecoveryCount,
                    `[${email}] /agreeTeam isteği`,
                    cloudFrontInfo,
                    { sleep: false },
                );
                const error = new Error(
                    `[${email}] /agreeTeam CloudFront 403 nedeniyle ` +
                    `${CONFIG.maxAttempts} kontrollü denemede tamamlanamadı` +
                    `${cloudFrontInfo.requestId ? ` (Request ID=${cloudFrontInfo.requestId})` : ''}.`,
                );
                error.preventRelogin = true;
                error.cloudFrontBlocked = true;
                error.retryAfterSeconds = Math.ceil(retryDelayMs / 1000);
                throw error;
            }

            await waitAfterCloudFrontBlock(
                cloudFrontRecoveryCount,
                `[${email}] /agreeTeam isteği`,
                cloudFrontInfo,
            );
            state = await openEventPage(page, leaderContext.link);
            if (membershipMatches(state, roleName, leaderContext)) {
                verifiedState = state;
                recoveredFromNonSuccessResponse = true;
                break;
            }
            if (!state.acceptControl.visible) {
                const error = new Error(
                    `[${email}] CloudFront beklemesi sonrasında üyelik doğrulanmadı ve ` +
                    `"Kabul Et" ekranı görünmüyor. Aynı oturum korunarak çalışma durduruldu.`,
                );
                error.preventRelogin = true;
                throw error;
            }
            continue;
        }
        const acceptedResponse =
            (result.ok && responseStatus === 'success') || errorCode === 'ERR312';

        verifiedState = await inspectMembershipWithoutLeavingInvite(
            page,
            roleName,
            leaderContext,
        );
        if (verifiedState) {
            recoveredFromNonSuccessResponse = !acceptedResponse;
            break;
        }

        if (attempt < CONFIG.maxAttempts) {
            await sleep(2000);
            const panelStillVisible = await isAcceptVisible(page);
            console.log(
                `[${email}] 2 saniyelik kontrol: Kabul Et ekranı ` +
                `${panelStillVisible ? 'hâlâ açık' : 'kapalı'}; ` +
                `sunucu üyeliği doğrulanmadığı için aynı oturum korunuyor.`,
            );
            if (!panelStillVisible) {
                await openEventPage(page, leaderContext.link);
            }
        }
    }

    if (!verifiedState) {
        const diagnostics = [
            `sid=${state.sid ? 'var' : 'yok'}`,
            `ud=${state.ud ? 'var' : 'yok'}`,
            `roleid=${state.roleId ? 'var' : 'yok'}`,
            `teamud=${state.teamUid ? 'var' : 'yok'}`,
            `rol_adayı=${(state.roleCandidates || []).length}`,
            `mouse_tıklama=${result ? result.physicalMouseClickCount : 0}`,
            `content-type=${result && result.contentType ? result.contentType : 'yok'}`,
            `status-text=${result && result.httpStatusText ? result.httpStatusText : 'yok'}`,
            `panel_yanıt_süresince_açık=${Boolean(result && result.controlledPanelKeptOpenUntilResponse)}`,
        ].join(', ');
        const error = new Error(
            `/agreeTeam üyeliği aynı oturumda ${CONFIG.maxAttempts} denemede doğrulanamadı: ` +
            `${result ? describeApiFailure(result) : 'yanıt yok'} [${diagnostics}]`,
        );
        error.preventRelogin = true;
        throw error;
    }

    if (!(await closeInvitePanelAfterServerVerification(page))) {
        throw new Error('Sunucu doğrulamasından sonra "Kabul Et" paneli kapatılamadı.');
    }
    await sleep(2000);
    if (await isAcceptVisible(page)) {
        throw new Error('Sunucu doğrulamasından 2 saniye sonra "Kabul Et" ekranı yeniden geldi.');
    }
    console.log(
        `[${email}] Sunucu üyeliği doğrulandı; "Kabul Et" paneli kapandı ve ` +
        `2 saniyelik kontrolde geri gelmedi.`,
    );

    const persistentState = await verifyInvitationClosedTwice(
        page,
        roleName,
        leaderContext,
    );
    leaderContext.knownMembers.add(roleName);
    console.log(
        `[${email}] Üyelik sunucu takım listesinden doğrulandı: ` +
        `${verifiedState.teamMembers.join(', ')}; davet ekranı 2/2 kapalı.`,
    );
    return {
        roleName,
        state: persistentState,
        alreadyMember: errorCode === 'ERR312',
        evidence: {
            join_mode: recoveredFromNonSuccessResponse
                ? 'server_roster_confirmed_after_non_success_response'
                : errorCode === 'ERR312'
                    ? 'server_reported_already_in_team'
                    : 'controlled_physical_mouse_agree_team_success',
            role_name_source: roleNameSource,
            event_registration: state.memberEventRegistration,
            api: {
                endpoint: '/agreeTeam',
                method: 'POST',
                response_observed: true,
                request_payload_fields_verified: ['user_id', 'um', 'teamuid'],
                http_status: result.httpStatus,
                response_status: responseStatus || null,
                error_code: errorCode || null,
                controlled_request_attempts: controlledRequestAttempt,
                cloudfront_recovery_count: cloudFrontRecoveryCount,
                panel_kept_open_until_server_verification: true,
            },
            server: {
                expected_leader_role: leaderContext.roleName,
                expected_member_role: roleName,
                roster: persistentState.teamMembers,
                membership_match: true,
            },
            invitation_ui: {
                dismissed_immediately: false,
                dismissed_only_after_server_verification: true,
                physical_mouse_click_count: result.physicalMouseClickCount,
                devtools_reflow_simulated: true,
                site_navigation_observed: result.navigatedAfterSuccess,
                persistent_closed_checks: 2,
                persistent_closed: true,
            },
        },
    };
}

function configureAutomationPage(page) {
    page.setDefaultTimeout(CONFIG.actionTimeoutMs);
    page.setDefaultNavigationTimeout(CONFIG.navigationTimeoutMs);
}

function findInstalledChrome() {
    const candidates = [
        process.env.LEGEND_CHROME_PATH,
        path.join(process.env.PROGRAMFILES || 'C:\\Program Files', 'Google', 'Chrome', 'Application', 'chrome.exe'),
        path.join(process.env['PROGRAMFILES(X86)'] || 'C:\\Program Files (x86)', 'Google', 'Chrome', 'Application', 'chrome.exe'),
        process.env.LOCALAPPDATA
            ? path.join(process.env.LOCALAPPDATA, 'Google', 'Chrome', 'Application', 'chrome.exe')
            : null,
    ].filter(Boolean);
    return candidates.find((candidate) => fs.existsSync(candidate)) || null;
}

async function launchAutomationBrowser() {
    const executablePath = findInstalledChrome();
    if (!executablePath) {
        throw new Error(
            'Kurulu Google Chrome bulunamadı. LEGEND_CHROME_PATH ile chrome.exe yolu verilmelidir.',
        );
    }
    console.log(`Kurulu Google Chrome kullanılıyor: ${executablePath}`);
    return puppeteer.launch({
        executablePath,
        headless: CONFIG.headless,
        defaultViewport: { width: 1366, height: 900 },
        args: CONFIG.headless
            ? ['--no-first-run', '--no-default-browser-check']
            : [
                '--incognito',
                '--start-minimized',
                '--window-position=-32000,-32000',
                '--window-size=1366,900',
                '--no-first-run',
                '--no-default-browser-check',
            ],
    });
}

async function processAccount(account, leaderContext, browser) {
    const { email, index, position } = account;
    const incognitoContext = await browser.createBrowserContext();

    try {
        const loginPage = await incognitoContext.newPage();
        configureAutomationPage(loginPage);
        await login(loginPage, email);

        if (position === 1) {
            if (!account.positionAssignedByQueue && !isLeader(index)) {
                throw new Error(`${index}. hesap 1. üye olduğu halde lider numarası kuralına uymuyor.`);
            }
            return {
                kind: 'leader',
                leaderContext: await createLeaderContext(loginPage, account),
            };
        }

        if (!leaderContext) {
            throw new Error(
                `${index}. hesap takım lideri değil ancak aktif lider davet linki yok. ` +
                `Çalışma aralığı i % ${CONFIG.groupSize} === 1 olan bir liderle başlamalıdır.`,
            );
        }

        console.log(
            `[${email}] Giriş ilk gizli sekmede doğrulandı; lider linki için ikinci sekme açılıyor...`,
        );
        const invitationPage = await incognitoContext.newPage();
        configureAutomationPage(invitationPage);
        await invitationPage.bringToFront();
        const membership = await joinLeaderTeam(
            invitationPage,
            account,
            leaderContext,
        );
        membership.evidence.browser_flow = {
            private_browser_context: true,
            login_tab: 'first_tab',
            invitation_tab: 'second_tab',
            leader_link_source: 'in_memory_from_group_leader',
            same_private_context_for_member_tabs: true,
        };
        return { kind: 'member', membership };
    } finally {
        await incognitoContext.close().catch(() => {});
        console.log(`[${email}] Gizli hesap oturumu kapatıldı.`);
    }
}

function accountRecordFor(groupRecord, position) {
    const record = groupRecord.accounts.find((account) => account.position === position);
    if (!record) {
        throw new Error(
            `${groupRecord.group_number}. grup içinde ${position}. üye kaydı bulunamadı.`,
        );
    }
    return record;
}

function pushAttemptHistory(accountRecord, entry) {
    accountRecord.attempt_history.push({ at: nowIso(), ...entry });
    if (accountRecord.attempt_history.length > 50) {
        accountRecord.attempt_history = accountRecord.attempt_history.slice(-50);
    }
}

function recordLeaderSuccess(state, groupRecord, accountRecord, result, runId) {
    const context = result.leaderContext;
    const confirmedAt = nowIso();
    accountRecord.grouping_status = 'leader_confirmed';
    accountRecord.actual_role_name = context.roleName;
    accountRecord.confirmed_at = confirmedAt;
    accountRecord.last_error = null;
    accountRecord.evidence = {
        run_id: runId,
        role_matches_verified_nickname:
            context.roleName === accountRecord.nickname_from_verified_accounts,
        role_name_source: context.roleNameSource,
        role_binding_verified: true,
        server_id: context.serverId,
        role_id: context.roleId,
        initial_server_roster: context.initialRoster,
        invite_link: {
            full_url_stored: false,
            reason: 'um ve kullanıcı kimliği içeren davet URLsi güvenlik için saklanmaz.',
            sha256: sha256(context.link),
            runtime_lifetime: 'memory_only_until_current_group_finishes',
        },
    };
    pushAttemptHistory(accountRecord, {
        run_id: runId,
        attempt: accountRecord.grouping_attempt_count,
        outcome: 'leader_confirmed',
        role_name: context.roleName,
    });

    groupRecord.invite = {
        generated_at: confirmedAt,
        generated_by_position: 1,
        generated_by_account_index: accountRecord.account_index,
        generated_by_email: accountRecord.email,
        invitation_type: 'team',
        endpoint_origin: new URL(CONFIG.eventUrl).origin,
        query_fields: ['sid', 'ud', 'type', 'shareuid', 'um'],
        full_url_stored: false,
        url_sha256: sha256(context.link),
        runtime_lifetime: 'memory_only_until_current_group_finishes',
        server_id: context.serverId,
    };
    groupRecord.verification.last_server_roster = context.initialRoster;
    groupRecord.verification.last_checked_at = confirmedAt;
    appendGroupEvent(groupRecord, {
        run_id: runId,
        type: 'leader_invite_generated',
        account_index: accountRecord.account_index,
        role_name: context.roleName,
        invite_url_sha256: sha256(context.link),
    });
    reconcileGroupAccountsFromRoster(
        groupRecord,
        context.initialRoster,
        runId,
    );
    recomputeGroupRecord(groupRecord);
    persistConfirmedGroupState(state);
}

function recordMemberSuccess(state, groupRecord, accountRecord, result, runId) {
    const membership = result.membership;
    const confirmedAt = nowIso();
    accountRecord.grouping_status = 'membership_confirmed';
    accountRecord.actual_role_name = membership.roleName;
    accountRecord.confirmed_at = confirmedAt;
    accountRecord.last_error = null;
    accountRecord.evidence = {
        run_id: runId,
        role_matches_verified_nickname:
            membership.roleName === accountRecord.nickname_from_verified_accounts,
        already_member_before_request: membership.alreadyMember,
        ...membership.evidence,
    };
    pushAttemptHistory(accountRecord, {
        run_id: runId,
        attempt: accountRecord.grouping_attempt_count,
        outcome: 'membership_confirmed',
        role_name: membership.roleName,
        join_mode: membership.evidence.join_mode,
    });

    groupRecord.verification.last_server_roster = membership.state.teamMembers;
    groupRecord.verification.last_checked_at = confirmedAt;
    appendGroupEvent(groupRecord, {
        run_id: runId,
        type: 'member_membership_confirmed',
        position: accountRecord.position,
        account_index: accountRecord.account_index,
        role_name: membership.roleName,
        join_mode: membership.evidence.join_mode,
        invitation_closed_checks: 2,
        server_roster: membership.state.teamMembers,
    });
    reconcileGroupAccountsFromRoster(
        groupRecord,
        membership.state.teamMembers,
        runId,
    );
    recomputeGroupRecord(groupRecord);
    persistConfirmedGroupState(state);
}

async function processAccountWithRetries(
    account,
    leaderContext,
    state,
    groupRecord,
    runId,
    browser,
) {
    const accountRecord = accountRecordFor(groupRecord, account.position);
    const confirmedBeforeRun =
        accountRecord.grouping_status === 'leader_confirmed' ||
        accountRecord.grouping_status === 'membership_confirmed';

    for (let attempt = 1; attempt <= CONFIG.maxAttempts; attempt += 1) {
        accountRecord.grouping_attempt_count += 1;
        accountRecord.last_attempt_at = nowIso();
        if (!confirmedBeforeRun) {
            accountRecord.grouping_status = account.position === 1
                ? 'leader_processing'
                : 'membership_processing';
        }
        pushAttemptHistory(accountRecord, {
            run_id: runId,
            attempt: accountRecord.grouping_attempt_count,
            run_attempt: attempt,
            outcome: 'started',
        });
        appendGroupEvent(groupRecord, {
            run_id: runId,
            type: 'account_attempt_started',
            position: account.position,
            account_index: account.index,
            run_attempt: attempt,
        });
        recomputeGroupRecord(groupRecord);
        persistConfirmedGroupState(state);

        try {
            console.log(`\n[${account.email}] Deneme ${attempt}/${CONFIG.maxAttempts}`);
            const result = await processAccount(account, leaderContext, browser);
            if (result.kind === 'leader') {
                recordLeaderSuccess(state, groupRecord, accountRecord, result, runId);
            } else {
                recordMemberSuccess(state, groupRecord, accountRecord, result, runId);
            }
            console.log(`[${account.email}] Hesap aşaması kesin olarak tamamlandı.`);
            console.log(
                `[${account.email}] Sonraki hesap isteğinden önce ` +
                `${Math.ceil(CONFIG.accountCooldownMs / 1000)} sn güvenli soğuma uygulanıyor...`,
            );
            await sleep(CONFIG.accountCooldownMs);
            return result;
        } catch (error) {
            if (!confirmedBeforeRun) {
                accountRecord.grouping_status = account.position === 1
                    ? 'leader_retry_pending'
                    : 'membership_retry_pending';
            }
            accountRecord.last_error = {
                at: nowIso(),
                message: error.message,
                run_id: runId,
                run_attempt: attempt,
            };
            pushAttemptHistory(accountRecord, {
                run_id: runId,
                attempt: accountRecord.grouping_attempt_count,
                run_attempt: attempt,
                outcome: 'failed',
                error: error.message,
            });
            appendGroupEvent(groupRecord, {
                run_id: runId,
                type: 'account_attempt_failed',
                position: account.position,
                account_index: account.index,
                run_attempt: attempt,
                error: error.message,
            });
            recomputeGroupRecord(groupRecord);
            persistConfirmedGroupState(state);

            console.error(`[${account.email}] Doğrulama başarısız: ${error.message}`);
            if (error.preventRelogin) {
                accountRecord.grouping_status = account.position === 1
                    ? 'leader_failed'
                    : 'membership_failed';
                recomputeGroupRecord(groupRecord);
                persistConfirmedGroupState(state);
                throw error;
            }
            if (attempt < CONFIG.maxAttempts) {
                const delay = Math.max(
                    Math.min(CONFIG.retryDelayMs * attempt, 15000),
                    CONFIG.accountCooldownMs,
                );
                console.log(
                    `[${account.email}] Sonraki hesaba geçilmeden aynı hesap ` +
                    `${Math.ceil(delay / 1000)} sn sonra yeniden denenecek.`,
                );
                await sleep(delay);
            }
        }
    }

    if (!confirmedBeforeRun) {
        accountRecord.grouping_status = account.position === 1
            ? 'leader_failed'
            : 'membership_failed';
    }
    recomputeGroupRecord(groupRecord);
    persistConfirmedGroupState(state);
    throw new Error(
        `${account.email} ${CONFIG.maxAttempts} denemede doğrulanamadı. ` +
        `Güvenlik gereği sıradaki üyeye veya gruba geçilmedi.`,
    );
}

function printExecutionPlan(executionPlan, selection) {
    console.log(
        `\nSeçim: ${selection.groupNumber}. grup, ${selection.memberPosition}. üyeden başlangıç.`,
    );
    console.log('Uygulanacak sıra:');
    for (const item of executionPlan) {
        const memberPositions = item.group.accounts
            .filter((account) => account.position >= item.memberStartPosition)
            .map((account) => account.position);
        console.log(
            `  ${item.group.groupNumber}. grup: önce lider ${item.group.accounts[0].index}; ` +
            `sonra üyeler ${memberPositions.join(', ') || 'yok'}`,
        );
    }
}

function buildBatchSourceData(batch) {
    if (!batch || !Number.isInteger(batch.sequence) || batch.sequence <= 0) {
        throw new Error('Otonom grup paketinde pozitif sequence gereklidir.');
    }
    if (!Array.isArray(batch.accounts) || batch.accounts.length !== CONFIG.groupSize) {
        throw new Error(`Otonom grup paketi tam olarak ${CONFIG.groupSize} hesap içermelidir.`);
    }
    const seenEmails = new Set();
    const accounts = batch.accounts.map((rawAccount, offset) => {
        const email = String(rawAccount.email || '').trim().toLowerCase();
        const nickname = String(rawAccount.nickname || '').trim();
        const index = Number(rawAccount.index);
        if (!email || seenEmails.has(email) || !nickname || !Number.isSafeInteger(index) || index <= 0) {
            throw new Error(`Otonom pakette geçersiz/tekrarlı hesap var: ${email || '(boş)'}`);
        }
        seenEmails.add(email);
        return {
            index,
            email,
            nickname,
            completedAt: String(rawAccount.created_at || ''),
            sourceVerification: { autonomous_pipeline: true, package_id: batch.id },
            groupNumber: batch.sequence,
            position: offset + 1,
            positionAssignedByQueue: true,
        };
    });
    const group = {
        groupNumber: batch.sequence,
        firstIndex: accounts[0].index,
        lastIndex: accounts[accounts.length - 1].index,
        accounts,
    };
    const serialized = JSON.stringify({ id: batch.id, sequence: batch.sequence, accounts });
    return {
        accounts,
        completeGroups: [group],
        incompleteGroups: [],
        sourceHash: sha256(serialized),
        sourceVersion: 1,
        autonomousPackageId: batch.id,
    };
}

function assertBatchGroupSlotAvailable(sourceData) {
    if (!sourceData.autonomousPackageId || !fs.existsSync(CONFIRMED_GROUPS_PATH)) {
        return;
    }
    const state = parseJson(fs.readFileSync(CONFIRMED_GROUPS_PATH, 'utf8'));
    const group = sourceData.completeGroups[0];
    const previous = state && state.groups && state.groups[String(group.groupNumber)];
    if (!previous || !Array.isArray(previous.accounts)) {
        return;
    }
    const previousEmails = previous.accounts.map((account) => String(account.email).toLowerCase());
    const requestedEmails = group.accounts.map((account) => account.email);
    if (JSON.stringify(previousEmails) !== JSON.stringify(requestedEmails)) {
        throw new Error(
            `${group.groupNumber}. grup numarası onaylanmis_gruplar.json içinde başka hesaplara ait. ` +
            'Durum dosyaları elle birleştirilmeden otomasyon devam etmeyecek.',
        );
    }
}

async function runGrouping(sourceData, selection) {
    assertBatchGroupSlotAvailable(sourceData);
    const executionPlan = buildExecutionPlan(sourceData, selection);
    printExecutionPlan(executionPlan, selection);

    if (CONFIG.planOnly) {
        console.log('\n--plan etkin: tarayıcı açılmadı, istek gönderilmedi, JSON değiştirilmedi.');
        return;
    }

    console.log(
        `\nGruplama başlıyor | tarayıcı=${CONFIG.headless ? 'headless' : 'gerçek gizli pencere'} | ` +
        `tam grup=${sourceData.completeGroups.length}`,
    );
    console.log(
        `Her üye /agreeTeam yanıtı, sunucu takım listesi ve 2 ardışık kapalı davet ` +
        `ekranı kontrolü tamamlanmadan sonraki üyeye geçmez.`,
    );

    const state = loadConfirmedGroupState(sourceData);
    const run = {
        run_id: crypto.randomUUID(),
        started_at: nowIso(),
        completed_at: null,
        status: 'running',
        requested_start_group: selection.groupNumber,
        requested_start_member_position: selection.memberPosition,
        browser_mode: CONFIG.headless ? 'headless' : 'incognito_visible',
        planned_groups: executionPlan.map((item) => item.group.groupNumber),
        completed_groups_during_run: [],
        error: null,
    };
    state.runs.push(run);
    if (state.runs.length > 100) {
        state.runs = state.runs.slice(-100);
    }
    persistConfirmedGroupState(state);

    let browser = null;
    try {
        browser = await launchAutomationBrowser();
        for (let itemIndex = 0; itemIndex < executionPlan.length; itemIndex += 1) {
            const item = executionPlan[itemIndex];
            const { group } = item;
            const groupRecord = ensureGroupRecord(state, group);
            appendGroupEvent(groupRecord, {
                run_id: run.run_id,
                type: 'group_processing_started',
                requested_start_position: item.requestedStartPosition,
                actual_member_start_position: item.memberStartPosition,
            });
            persistConfirmedGroupState(state);

            const leaderAccount = group.accounts.find((account) => account.position === 1);
            const leaderResult = await processAccountWithRetries(
                leaderAccount,
                null,
                state,
                groupRecord,
                run.run_id,
                browser,
            );
            const leaderContext = leaderResult.leaderContext;

            const membersToProcess = group.accounts.filter(
                (account) => account.position >= item.memberStartPosition,
            );
            for (const member of membersToProcess) {
                await processAccountWithRetries(
                    member,
                    leaderContext,
                    state,
                    groupRecord,
                    run.run_id,
                    browser,
                );
            }

            recomputeGroupRecord(groupRecord);
            appendGroupEvent(groupRecord, {
                run_id: run.run_id,
                type: 'group_processing_finished',
                final_status: groupRecord.status,
                confirmed_positions: groupRecord.verification.confirmed_positions,
            });
            if (groupRecord.status === 'confirmed') {
                run.completed_groups_during_run.push(group.groupNumber);
                console.log(`\n${group.groupNumber}. grup dört üyesiyle kesin onaylandı.`);
            } else {
                console.log(
                    `\n${group.groupNumber}. grup seçilen başlangıç nedeniyle kısmi kaldı; ` +
                    `onaylı konumlar: ` +
                    `${groupRecord.verification.confirmed_positions.join(', ') || 'yok'}.`,
                );
            }
            leaderContext.link = null;
            appendGroupEvent(groupRecord, {
                run_id: run.run_id,
                type: 'leader_invite_removed_from_runtime_memory',
            });
            persistConfirmedGroupState(state);

            if (itemIndex < executionPlan.length - 1) {
                console.log(
                    `Sonraki gruba geçmeden önce ${Math.ceil(CONFIG.groupCooldownMs / 1000)} sn ` +
                    `CloudFront güvenli grup soğuması uygulanıyor...`,
                );
                await sleep(CONFIG.groupCooldownMs);
            }
        }

        run.status = 'completed';
        run.completed_at = nowIso();
        persistConfirmedGroupState(state);
        console.log(
            `\nSeçilen noktadan sonraki tüm uygun hesaplar doğrulandı. Ayrıntılı kayıt: ` +
            `${CONFIRMED_GROUPS_PATH}`,
        );
    } catch (error) {
        run.status = 'failed';
        run.completed_at = nowIso();
        run.error = { at: nowIso(), message: error.message };
        persistConfirmedGroupState(state);
        throw error;
    } finally {
        if (browser) {
            await browser.close().catch(() => {});
        }
    }
}

async function runGroupingBatch(batch) {
    const sourceData = buildBatchSourceData(batch);
    return runGrouping(sourceData, {
        groupNumber: batch.sequence,
        memberPosition: 1,
    });
}

async function main() {
    const sourceData = loadVerifiedGroups();
    const selection = await promptStartSelection(sourceData);
    return runGrouping(sourceData, selection);
}

if (require.main === module) {
    main().catch((error) => {
        console.error(`\nGruplama durduruldu: ${error.message}`);
        process.exitCode = 1;
    });
}

module.exports = {
    buildLeaderLink,
    buildBatchSourceData,
    buildExecutionPlan,
    isLeader,
    isCloudFrontSignature,
    logLeaderInviteLink,
    loadConfirmedGroupState,
    loadVerifiedGroups,
    normalizedRoleName,
    persistConfirmedGroupState,
    runGroupingBatch,
    selectMemberRegistrationRole,
};
