'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');

const {
    buildBatchSourceData,
    buildLeaderLink,
    buildExecutionPlan,
    isLeader,
    isCloudFrontSignature,
    logLeaderInviteLink,
    loadConfirmedGroupState,
    loadVerifiedGroups,
    normalizedRoleName,
    persistConfirmedGroupState,
    selectMemberRegistrationRole,
} = require('./grupla');

function createVerifiedAccountsFixture() {
    const temporaryDirectory = fs.mkdtempSync(
        path.join(os.tmpdir(), 'legendbots-verified-'),
    );
    const target = path.join(temporaryDirectory, 'completed_accounts.json');
    const completedAccounts = {};
    for (let index = 1; index <= 12; index += 1) {
        completedAccounts[`hadestxz${index}@outlook.com`] = {
            nickname: `NICK${index}`,
            completed_at: `2026-07-21T10:${String(index).padStart(2, '0')}:00+03:00`,
            verification: { test_fixture: true },
        };
    }
    fs.writeFileSync(target, JSON.stringify({ version: 1, completed_accounts: completedAccounts }));
    return { temporaryDirectory, target };
}

function withVerifiedAccountsFixture(callback) {
    const fixture = createVerifiedAccountsFixture();
    try {
        return callback(loadVerifiedGroups(fixture.target));
    } finally {
        fs.rmSync(fixture.temporaryDirectory, { recursive: true, force: true });
    }
}

test('CloudFront 403 sayfasını durum kodu veya gövde imzasından tanır', () => {
    assert.equal(isCloudFrontSignature(403, '', ''), true);
    assert.equal(
        isCloudFrontSignature(
            200,
            'ERROR: The request could not be satisfied',
            '403 ERROR\nGenerated by cloudfront (CloudFront)\nRequest ID: test-id',
        ),
        true,
    );
    assert.equal(isCloudFrontSignature(200, 'Legend Online', 'Kabul Et'), false);
});

test('liderin tam davet linkini JSON satırı olarak günlüğe yazar', () => {
    const temporaryDirectory = fs.mkdtempSync(
        path.join(os.tmpdir(), 'legendbots-link-log-'),
    );
    const target = path.join(temporaryDirectory, 'grupla.log');
    const inviteUrl = 'https://example.test/activity?sid=1411&ud=1&type=team&shareuid=2&um=test';

    try {
        logLeaderInviteLink(
            { groupNumber: 3, index: 9, email: 'leader@example.test' },
            'LiderRol',
            inviteUrl,
            target,
        );
        const lines = fs.readFileSync(target, 'utf8').trim().split(/\r?\n/);
        const entry = JSON.parse(lines[0]);
        assert.equal(lines.length, 1);
        assert.equal(entry.event, 'leader_invite_link_created');
        assert.equal(entry.group_number, 3);
        assert.equal(entry.leader_account_index, 9);
        assert.equal(entry.invite_url, inviteUrl);
    } finally {
        fs.rmSync(temporaryDirectory, { recursive: true, force: true });
    }
});

test('lider linkini verilen parametre sırasıyla birebir oluşturur', () => {
    assert.equal(
        buildLeaderLink({
            sid: '1411',
            ud: '123456',
            user_id: '987654321',
            um: 'abcdef0123456789',
        }),
        'https://newserver79-lotr.oasgames.com/activity' +
            '?sid=1411&ud=123456&type=team&shareuid=987654321&um=abcdef0123456789',
    );
});

test('sunucu kadrosundaki rol adlarını büyük küçük harften bağımsız eşler', () => {
    assert.equal(normalizedRoleName('Kivilcim'), normalizedRoleName('kivilcim'));
    assert.equal(normalizedRoleName(' Q4UONT7TTSLA '), 'q4uont7ttsla');
});

test('üye kaydı için lider sunucusu ve doğrulanmış nickname ile doğru rolü seçer', () => {
    const role = selectMemberRegistrationRole(
        [
            { sid: '1409', roleName: 'RUBYIM9Z6Y3Z', roleId: 'old' },
            { sid: '1411', roleName: 'rubyim9z6y3z', roleId: 'expected' },
            { sid: '1411', roleName: 'BaşkaRol', roleId: 'other' },
        ],
        '1411',
        'RUBYIM9Z6Y3Z',
    );
    assert.equal(role.roleId, 'expected');
});

test('existing_account yer tutucusunu lider sunucusundaki gerçek rolle çözer', () => {
    const roles = [
        { sid: '1411', roleName: 'head', roleId: '1' },
        { sid: '1410', roleName: 'Boş', roleId: '2' },
    ];
    assert.equal(
        selectMemberRegistrationRole(roles, '1411', 'existing_account').roleName,
        'head',
    );
});

test('lider hesaplar 1, 5, 9, 13 kuralını izler', () => {
    for (const leader of [1, 5, 9, 13, 17]) {
        assert.equal(isLeader(leader), true);
    }
    for (const member of [2, 3, 4, 6, 7, 8, 10, 11, 12]) {
        assert.equal(isLeader(member), false);
    }
});

test('doğrulanmış hesaplar numaralarına göre tam dörtlü gruplara ayrılır', () => {
    withVerifiedAccountsFixture((source) => {
        assert.deepEqual(
            source.completeGroups.map((group) =>
                group.accounts.map((account) => account.index),
            ),
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
            ],
        );
        assert.deepEqual(
            source.completeGroups.map((group) => group.accounts[0].index),
            [1, 5, 9],
        );
    });
});

test('seçilen üye konumundan başlar ve sonraki grupları baştan işler', () => {
    withVerifiedAccountsFixture((source) => {
        const plan = buildExecutionPlan(source, { groupNumber: 2, memberPosition: 3 });
        assert.deepEqual(
            plan.map((item) => ({
                group: item.group.groupNumber,
                leader: item.group.accounts[0].index,
                members: item.group.accounts
                    .filter((account) => account.position >= item.memberStartPosition)
                    .map((account) => account.index),
            })),
            [
                { group: 2, leader: 5, members: [7, 8] },
                { group: 3, leader: 9, members: [10, 11, 12] },
            ],
        );
    });
});

test('1. üye seçildiğinde liderden sonra aynı grubun 2, 3, 4 üyeleri işlenir', () => {
    withVerifiedAccountsFixture((source) => {
        const plan = buildExecutionPlan(source, { groupNumber: 1, memberPosition: 1 });
        assert.deepEqual(
            plan[0].group.accounts
                .filter((account) => account.position >= plan[0].memberStartPosition)
                .map((account) => account.index),
            [2, 3, 4],
        );
    });
});

test('ayrıntılı grup durumu atomik JSON olarak yazılıp yeniden okunur', () => {
    const temporaryDirectory = fs.mkdtempSync(
        path.join(os.tmpdir(), 'legendbots-grupla-'),
    );
    const target = path.join(temporaryDirectory, 'onaylanmis_gruplar.json');

    try {
        const fixture = createVerifiedAccountsFixture();
        const source = loadVerifiedGroups(fixture.target);
        const state = loadConfirmedGroupState(source, target);
        persistConfirmedGroupState(state, target);
        state.updated_by_test = true;
        persistConfirmedGroupState(state, target);

        const serialized = fs.readFileSync(target, 'utf8');
        const parsed = JSON.parse(serialized);
        assert.equal(parsed.file_type, 'legendbots_confirmed_groups');
        assert.equal(parsed.source.verified_account_count, 12);
        assert.deepEqual(Object.keys(parsed.groups), ['1', '2', '3']);
        assert.equal(parsed.groups['1'].leader_account_index, 1);
        assert.equal(parsed.groups['2'].leader_account_index, 5);
        assert.equal(parsed.groups['3'].leader_account_index, 9);
        assert.equal(parsed.groups['1'].accounts.length, 4);
        assert.equal(parsed.updated_by_test, true);
        assert.equal(serialized.includes('123321'), false);
        assert.equal(fs.existsSync(`${target}.tmp`), false);
        assert.equal(fs.existsSync(`${target}.bak`), false);
        fs.rmSync(fixture.temporaryDirectory, { recursive: true, force: true });
    } finally {
        fs.rmSync(temporaryDirectory, { recursive: true, force: true });
    }
});

test('otonom kuyruk dört eski hesabı sıra konumlarıyla tek pakete dönüştürür', () => {
    const source = buildBatchSourceData({
        id: 'group-000123',
        sequence: 123,
        accounts: [41, 7, 99, 12].map((index) => ({
            email: `hadestxz${index}@outlook.com`,
            index,
            nickname: `NICK${index}`,
            created_at: '2026-07-21T10:00:00+03:00',
        })),
    });
    assert.equal(source.completeGroups.length, 1);
    assert.equal(source.completeGroups[0].groupNumber, 123);
    assert.deepEqual(source.completeGroups[0].accounts.map((account) => account.position), [1, 2, 3, 4]);
    assert.equal(source.completeGroups[0].accounts[0].positionAssignedByQueue, true);
});
