'use strict';

const fs = require('node:fs');
const path = require('node:path');
const {
    REWARD_MILESTONES,
    computeRateLimitBackoffMs,
    networkCooldownDelay,
    penalizeNetworkScope,
    reserveNetworkSlot,
} = require('./pipeline/core');
const { passwordForEmail } = require('./pipeline/credentials');
const {
    applyRuntimeTiming: applySignRuntimeTiming,
    confirmSign,
    launchBrowser,
    login,
    isRecoverableBrowserSessionError,
    openVerifiedEventSession,
    runSignPackage,
} = require('./sign');

const BASE_DIR = __dirname;
const TOPLANAN_KODLAR_PATH = path.join(BASE_DIR, 'ToplananKodlar.txt');
const ACTIVITY_URL = 'https://newserver79-lotr.oasgames.com/activity';

function positiveInteger(name, fallback, minimum = 1) {
    const raw = process.env[name];
    if (raw == null || raw === '') {
        return fallback;
    }
    const value = Number.parseInt(raw, 10);
    if (!Number.isInteger(value) || value <= 0) {
        throw new Error(`${name} pozitif tam sayı olmalıdır.`);
    }
    return Math.max(value, minimum);
}

const CONFIG = {
    actionTimeoutMs: positiveInteger('LEGEND_REWARD_ACTION_TIMEOUT_MS', 30000),
    navigationIntervalMs: positiveInteger('LEGEND_NAVIGATION_INTERVAL_MS', 15000, 15000),
    maxAttempts: positiveInteger('LEGEND_REWARD_MAX_ATTEMPTS', 8, 3),
    verificationDelayMs: positiveInteger('LEGEND_REWARD_VERIFICATION_DELAY_MS', 3000, 1000),
    cloudFrontBackoffMs: positiveInteger('LEGEND_CLOUDFRONT_BACKOFF_MS', 120000, 120000),
    cloudFrontBackoffMaxMs: positiveInteger('LEGEND_CLOUDFRONT_BACKOFF_MAX_MS', 900000, 900000),
    cloudFrontMaxAttempts: positiveInteger('LEGEND_CLOUDFRONT_MAX_ATTEMPTS', 3, 3),
};

function applyRuntimeTiming(timing = {}) {
    const integerAtLeast = (value, fallback, minimum) => {
        const numeric = Number(value);
        return Number.isFinite(numeric) ? Math.max(minimum, Math.round(numeric)) : fallback;
    };
    CONFIG.navigationIntervalMs = integerAtLeast(
        timing.networkIntervalMs,
        CONFIG.navigationIntervalMs,
        3000,
    );
    CONFIG.cloudFrontBackoffMs = integerAtLeast(
        Number(timing.cloudFrontBackoffBaseSeconds) * 1000,
        CONFIG.cloudFrontBackoffMs,
        30000,
    );
    CONFIG.cloudFrontBackoffMaxMs = Math.max(
        CONFIG.cloudFrontBackoffMs,
        integerAtLeast(
            Number(timing.cloudFrontBackoffMaxSeconds) * 1000,
            CONFIG.cloudFrontBackoffMaxMs,
            300000,
        ),
    );
    applySignRuntimeTiming(timing);
    return { ...CONFIG };
}

function sleep(milliseconds) {
    return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function isCloudFrontSignature(status, text) {
    return status === 403 ||
        /403\s+ERROR/i.test(text || '') ||
        /request could not be satisfied/i.test(text || '') ||
        /generated by cloudfront/i.test(text || '');
}

function retryAfterMilliseconds(raw) {
    if (!raw) {
        return 0;
    }
    const seconds = Number(raw);
    if (Number.isFinite(seconds)) {
        return Math.max(0, seconds * 1000);
    }
    const date = Date.parse(raw);
    return Number.isFinite(date) ? Math.max(0, date - Date.now()) : 0;
}

async function waitForNetworkTurn(label) {
    const cooldownDelay = await networkCooldownDelay('reward');
    if (cooldownDelay > 0) {
        console.log(`[${label}] BOT 4 403 soğuması: ${Math.ceil(cooldownDelay / 1000)} sn.`);
        await sleep(cooldownDelay);
    }
    const gateDelay = await reserveNetworkSlot(ACTIVITY_URL, CONFIG.navigationIntervalMs);
    if (gateDelay > 0) {
        console.log(`[${label}] Ortak CloudFront sırası: ${Math.ceil(gateDelay / 1000)} sn.`);
        await sleep(gateDelay);
    }
}

function parseJsonResponse(text, label) {
    try {
        const parsed = JSON.parse(String(text || ''));
        if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
            throw new Error('nesne değil');
        }
        return parsed;
    } catch (error) {
        throw new Error(`${label} JSON yanıtı çözülemedi: ${error.message}.`);
    }
}

async function postActivityApi(page, endpoint, payload, label) {
    let lastRetryDelayMs = CONFIG.cloudFrontBackoffMs;
    for (let attempt = 1; attempt <= CONFIG.cloudFrontMaxAttempts; attempt += 1) {
        await waitForNetworkTurn(label);
        const result = await page.evaluate(async ({ target, fields, timeoutMs }) => {
            const body = new URLSearchParams(fields).toString();
            const controller = new AbortController();
            const timer = setTimeout(() => controller.abort(), timeoutMs);
            try {
                const response = await fetch(target, {
                    method: 'POST',
                    credentials: 'same-origin',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                        'X-Requested-With': 'XMLHttpRequest',
                    },
                    body,
                    signal: controller.signal,
                });
                return {
                    status: response.status,
                    text: await response.text(),
                    retryAfter: response.headers.get('retry-after') || '',
                };
            } finally {
                clearTimeout(timer);
            }
        }, { target: endpoint, fields: payload, timeoutMs: CONFIG.actionTimeoutMs });

        if (!isCloudFrontSignature(result.status, result.text)) {
            return { ...result, payload: parseJsonResponse(result.text, label) };
        }
        const requestedDelay = computeRateLimitBackoffMs(attempt, {
            baseMs: CONFIG.cloudFrontBackoffMs,
            maximumMs: CONFIG.cloudFrontBackoffMaxMs,
            serverDelayMs: retryAfterMilliseconds(result.retryAfter),
        });
        lastRetryDelayMs = await penalizeNetworkScope(ACTIVITY_URL, requestedDelay, undefined, {
            worker: 'reward',
            attempt,
            http_status: result.status,
        });
        if (attempt < CONFIG.cloudFrontMaxAttempts) {
            console.warn(`[${label}] CloudFront 403; BOT 4 ${Math.ceil(lastRetryDelayMs / 1000)} sn bekleyecek.`);
            await sleep(lastRetryDelayMs);
        }
    }
    const error = new Error(`${label} CloudFront engeli nedeniyle tamamlanamadı.`);
    error.isRateLimited = true;
    error.retryAfterSeconds = Math.ceil(lastRetryDelayMs / 1000);
    throw error;
}

async function getActivityApi(page, endpoint, label) {
    let lastRetryDelayMs = CONFIG.cloudFrontBackoffMs;
    for (let attempt = 1; attempt <= CONFIG.cloudFrontMaxAttempts; attempt += 1) {
        await waitForNetworkTurn(label);
        const result = await page.evaluate(async ({ target, timeoutMs }) => {
            const controller = new AbortController();
            const timer = setTimeout(() => controller.abort(), timeoutMs);
            try {
                const response = await fetch(target, {
                    method: 'GET',
                    credentials: 'same-origin',
                    headers: { 'X-Requested-With': 'XMLHttpRequest' },
                    signal: controller.signal,
                });
                return {
                    status: response.status,
                    text: await response.text(),
                    retryAfter: response.headers.get('retry-after') || '',
                };
            } finally {
                clearTimeout(timer);
            }
        }, { target: endpoint, timeoutMs: CONFIG.actionTimeoutMs });

        if (!isCloudFrontSignature(result.status, result.text)) {
            return { ...result, payload: parseJsonResponse(result.text, label) };
        }
        const requestedDelay = computeRateLimitBackoffMs(attempt, {
            baseMs: CONFIG.cloudFrontBackoffMs,
            maximumMs: CONFIG.cloudFrontBackoffMaxMs,
            serverDelayMs: retryAfterMilliseconds(result.retryAfter),
        });
        lastRetryDelayMs = await penalizeNetworkScope(ACTIVITY_URL, requestedDelay, undefined, {
            worker: 'reward',
            attempt,
            http_status: result.status,
        });
        if (attempt < CONFIG.cloudFrontMaxAttempts) {
            console.warn(`[${label}] CloudFront 403; BOT 4 ${Math.ceil(lastRetryDelayMs / 1000)} sn bekleyecek.`);
            await sleep(lastRetryDelayMs);
        }
    }
    const error = new Error(`${label} CloudFront engeli nedeniyle tamamlanamadı.`);
    error.isRateLimited = true;
    error.retryAfterSeconds = Math.ceil(lastRetryDelayMs / 1000);
    throw error;
}

function normalizeTeamCodes(payload) {
    const codes = payload && payload.codes;
    const team = codes && Array.isArray(codes.team) ? codes.team : [];
    return team
        .map((entry) => ({
            type: String(entry && entry.type || '').trim().toLowerCase(),
            code: String(entry && (entry.giftCode || entry.gift_code || entry.code) || '').trim(),
            receiveTime: (() => {
                const raw = entry && (entry.receiveTime || entry.receive_time);
                const numeric = Number(raw);
                if (Number.isFinite(numeric) && numeric > 0) {
                    return numeric;
                }
                const parsedDate = Date.parse(String(raw || ''));
                return Number.isFinite(parsedDate) ? parsedDate : 0;
            })(),
        }))
        .filter((entry) => entry.type && entry.code);
}

function normalizeRoleName(value) {
    return String(value || '').trim().toLocaleLowerCase('tr-TR');
}

function selectRewardRegistrationRole(roleCandidates, nickname) {
    const expected = normalizeRoleName(nickname);
    if (!expected) {
        return null;
    }
    return (roleCandidates || []).find((role) =>
        String(role && role.roleId || '').trim() &&
        normalizeRoleName(role && role.roleName) === expected
    ) || null;
}

async function readRewardRegistrationState(page) {
    return page.evaluate(() => {
        const normalize = (value) => String(value || '').trim();
        const inputValue = (root, selector) => {
            const input = root ? root.querySelector(selector) : null;
            return input ? normalize(input.value) : '';
        };
        const roleElements = Array.from(document.querySelectorAll('.ser_role_list li'));
        return {
            userId: normalize(window.user_id),
            um: normalize(window.um),
            ud: normalize(window.ud),
            roleCandidates: roleElements.map((role) => {
                const name = role.querySelector('.name');
                return {
                    sid: inputValue(role, '.server_id'),
                    roleId: inputValue(role, '.role_id'),
                    roleName: name ? normalize(name.textContent) : '',
                    serverName: inputValue(role, '.servername'),
                    roleGrade: inputValue(role, '.role_grade'),
                };
            }),
        };
    });
}

async function ensureRewardEventRegistration(page, email, session, account = {}, dependencies = {}) {
    if (session && session.ud) {
        return session;
    }
    const readRegistrationState = dependencies.readRewardRegistrationState ||
        readRewardRegistrationState;
    const postForm = dependencies.postActivityApi || postActivityApi;
    const reopenSession = dependencies.openVerifiedEventSession || openVerifiedEventSession;
    const state = await readRegistrationState(page);
    const current = { ...(session || {}), ...state };
    if (current.ud) {
        return current;
    }

    const role = selectRewardRegistrationRole(current.roleCandidates, account.nickname);
    if (!role) {
        const error = new Error(
            `${email}: ödül kullanıcısı oluşturulamadı; ` +
            `${account.nickname || 'kayıtlı karakter'} OAS rol listesinde bulunamadı.`,
        );
        error.isAccountRoleMissing = true;
        throw error;
    }

    console.log(
        `[BOT 4] [${email}] Ödül kullanıcı kaydı eksik; ` +
        `${role.sid}:${role.roleName} rolü /binding ile bağlanıyor...`,
    );
    const response = await postForm(page, '/binding', {
        user_id: current.userId,
        sid: role.sid,
        role_id: role.roleId,
        um: current.um,
        server_name: role.serverName,
        role_name: role.roleName,
        role_grade: role.roleGrade,
    }, `${email} ödül kullanıcı kaydı`);
    if (!response.payload || response.payload.status !== 'success') {
        const details = responseError(response.payload);
        const error = new Error(
            `${email}: ödül kullanıcı kaydı reddedildi ` +
            `(${details.code || 'kod yok'}${details.message ? `: ${details.message}` : ''}).`,
        );
        error.isSessionInvalid = /ERR901/i.test(details.code) || /user\s+is\s+null/i.test(details.message);
        throw error;
    }

    const verified = await reopenSession(page, email);
    if (!verified.ud) {
        const error = new Error(`${email}: /binding başarılıydı ancak ud sunucudan doğrulanamadı.`);
        error.isSessionInvalid = true;
        throw error;
    }
    console.log(`[BOT 4] [${email}] Ödül kullanıcı kaydı sunucudan doğrulandı.`);
    return verified;
}

function rewardCodeForMilestone(teamCodes, milestone) {
    const matches = teamCodes
        .filter((entry) => entry.type === milestone.codeType)
        .sort((left, right) => right.receiveTime - left.receiveTime);
    return matches.length ? matches[0].code : null;
}

function existingRewardObservations(teamCodes) {
    return REWARD_MILESTONES
        .map((milestone) => {
            const matches = teamCodes
                .filter((entry) => entry.type === milestone.codeType)
                .sort((left, right) => right.receiveTime - left.receiveTime);
            if (!matches.length) {
                return null;
            }
            return {
                threshold: milestone.threshold,
                level: milestone.level,
                codeType: milestone.codeType,
                code: matches[0].code,
                receiveTime: matches[0].receiveTime,
            };
        })
        .filter(Boolean);
}

async function fetchTeamCodes(page, email, session) {
    if (!session || !session.userId || !session.um) {
        throw new Error(`${email}: /userGiftCode için doğrulanmış etkinlik oturumu yok.`);
    }
    const response = await getActivityApi(
        page,
        '/userGiftCode',
        `${email} ödül kodu doğrulaması`,
    );
    const details = responseError(response.payload);
    const hasExplicitError = Boolean(
        details.code ||
        details.message ||
        (response.payload && response.payload.status === 'error') ||
        (response.payload && response.payload.status === 'fail'),
    );
    if (hasExplicitError) {
        const error = new Error(
            `${email}: /userGiftCode geçerli takım kodu listesi döndürmedi` +
            `${details.code || details.message ? ` (${details.code || 'kod yok'}${details.message ? `: ${details.message}` : ''})` : ''}.`,
        );
        error.isMissingRewardUser = /ERR1/i.test(details.code) || /user\s+is\s+null/i.test(details.message);
        throw error;
    }
    return normalizeTeamCodes(response.payload);
}

function responseError(payload) {
    const code = String(payload && (payload.err_code || payload.code) || '').trim();
    const message = String(
        payload && (payload.exception || payload.message || payload.msg || payload.error) || '',
    ).trim();
    return { code, message };
}

async function claimRewardMilestone(page, email, session, milestone, options = {}) {
    const codeFetcher = options.fetchTeamCodes || fetchTeamCodes;
    const claimPoster = options.postActivityApi || postActivityApi;
    const maximumAttempts = Math.max(1, Number(options.maxAttempts) || CONFIG.maxAttempts);
    let codes = Array.isArray(options.knownCodes) ? options.knownCodes : null;
    if (codes === null) {
        try {
            codes = await codeFetcher(page, email, session);
        } catch (error) {
            if (!error.isMissingRewardUser) {
                throw error;
            }
            // Üye hesabında ilk kod henüz üretilmediyse /userGiftCode ERR1 dönebilir.
            // Bu, ödülün kapalı olduğu anlamına gelmez; signGetCode ilk kaydı oluşturur.
            codes = [];
        }
    }
    let code = rewardCodeForMilestone(codes, milestone);
    if (code) {
        console.log(
            `[BOT 4] [${email}] ${milestone.threshold} eşiği sunucu kod listesinde zaten var; ` +
            'tekrar istek gönderilmeden uzlaştırıldı.',
        );
        return { code, reconciled: true };
    }

    for (let claimAttempt = 1; claimAttempt <= maximumAttempts; claimAttempt += 1) {
        const response = await claimPoster(page, '/signGetCode', {
            user_id: session.userId,
            um: session.um,
            sign_level: String(milestone.level),
        }, `${email} ${milestone.threshold} ödül eşiği`);

        if (response.payload.status === 'success') {
            break;
        }

        // Sunucu isteği uygulayıp bağlantıyı belirsiz bir yanıtla kapattıysa kod
        // listesi nihai otoritedir. Önce onu tekrar okuyup çift claim'i önle.
        try {
            codes = await codeFetcher(page, email, session);
        } catch (error) {
            if (!error.isMissingRewardUser) {
                throw error;
            }
            codes = [];
        }
        code = rewardCodeForMilestone(codes, milestone);
        if (code) {
            return { code, reconciled: true };
        }
        const details = responseError(response.payload);
        const sessionInvalid = /ERR901/i.test(details.code) || /user\s+is\s+null/i.test(details.message);
        if (sessionInvalid && claimAttempt < maximumAttempts) {
            console.warn(
                `[BOT 4] [${email}] ${milestone.threshold} eşiği geçici oturum reddi ` +
                `${claimAttempt}/${maximumAttempts}; aynı doğrulanmış oturumda tekrar denenecek.`,
            );
            continue;
        }
        const error = new Error(
            `${email}: ${milestone.threshold} ödül eşiği reddedildi ` +
            `(${details.code || 'kod yok'}${details.message ? `: ${details.message}` : ''}).`,
        );
        error.isSessionInvalid = sessionInvalid;
        // signGetCode, henüz açılmamış bir eşik için de normal bir HTTP yanıtı
        // döndürür. Uzak uzlaştırma bu deterministik retleri bağlantı/oturum
        // hatalarından ayırarak daha sonra yeniden deneyebilmelidir.
        error.isRewardUnavailable = !error.isSessionInvalid;
        error.rewardErrorCode = details.code || null;
        throw error;
    }

    for (let attempt = 1; attempt <= maximumAttempts; attempt += 1) {
        try {
            codes = await codeFetcher(page, email, session);
        } catch (error) {
            if (!error.isMissingRewardUser) {
                throw error;
            }
            codes = [];
        }
        code = rewardCodeForMilestone(codes, milestone);
        if (code) {
            console.log(`[BOT 4] [${email}] ${milestone.threshold} eşiği ödül kodu sunucudan doğrulandı.`);
            return { code, reconciled: false };
        }
        if (attempt < maximumAttempts) {
            await sleep(CONFIG.verificationDelayMs);
        }
    }
    throw new Error(
        `${email}: ${milestone.threshold} eşiği claim yanıtı başarılıydı ancak ödül kodu ` +
        `/userGiftCode içinde ${maximumAttempts} kontrolde görünmedi.`,
    );
}

function milestoneForThreshold(threshold) {
    return REWARD_MILESTONES.find((item) => item.threshold === Number(threshold)) || null;
}

function normalizeCollectedEmail(email) {
    const normalized = String(email || '').trim().toLowerCase();
    if (!/^[^\s@]+@[^\s@]+$/.test(normalized)) {
        throw new Error('Toplanan ödül kaydı için takma ad değil, tam hesap e-postası gereklidir.');
    }
    return normalized;
}

function collectedCodeLine(email, threshold, code) {
    const milestone = milestoneForThreshold(threshold);
    const normalizedEmail = normalizeCollectedEmail(email);
    const normalizedCode = String(code || '').trim();
    if (!milestone || !normalizedCode) {
        throw new Error('Toplanan ödül kaydı için tam e-posta, geçerli eşik ve kod gereklidir.');
    }
    return `${normalizedEmail} kod: ${normalizedCode}, type: ${milestone.codeType}, threshold: ${milestone.threshold}`;
}

function appendCollectedCode(email, threshold, code, targetPath = TOPLANAN_KODLAR_PATH) {
    const line = collectedCodeLine(email, threshold, code);
    const existing = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf8') : '';
    if (existing.split(/\r?\n/).some((existingLine) => existingLine === line)) {
        return false;
    }
    fs.appendFileSync(targetPath, `${line}\n`, { encoding: 'utf8', mode: 0o600 });
    console.log(`[BOT 4] ${normalizeCollectedEmail(email)} için ${threshold} eşiği yerel kod listesine kaydedildi.`);
    return true;
}

function writeCollectedCodesAtomically(targetPath, contents) {
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    const temporaryPath = `${targetPath}.${process.pid}.${Date.now()}.tmp`;
    try {
        fs.writeFileSync(temporaryPath, contents, { encoding: 'utf8', mode: 0o600 });
        try {
            fs.renameSync(temporaryPath, targetPath);
        } catch (error) {
            if (!['EEXIST', 'EPERM', 'EACCES'].includes(error && error.code)) {
                throw error;
            }
            fs.rmSync(targetPath, { force: true });
            fs.renameSync(temporaryPath, targetPath);
        }
    } finally {
        fs.rmSync(temporaryPath, { force: true });
    }
}

function synchronizeCollectedCodes(state, targetPath = TOPLANAN_KODLAR_PATH) {
    if (!state || !state.groups || typeof state.groups !== 'object') {
        throw new Error('ToplananKodlar uzlaştırması için geçerli pipeline state gereklidir.');
    }
    const records = [];
    for (const [groupId, group] of Object.entries(state.groups)) {
        const leaderEmail = Array.isArray(group.account_emails) ? group.account_emails[0] : null;
        for (const [threshold, stored] of Object.entries(group.reward_codes || {})) {
            if (!leaderEmail) {
                throw new Error(`${groupId} ödül kodu içeriyor ancak lider hesabı bulunmuyor.`);
            }
            const accountCodes = typeof stored === 'string'
                ? { [leaderEmail]: stored }
                : stored;
            if (!accountCodes || typeof accountCodes !== 'object' || Array.isArray(accountCodes)) {
                throw new Error(`${groupId}/${threshold} hesap bazlı ödül kodları geçersiz.`);
            }
            for (const [email, code] of Object.entries(accountCodes)) {
                const position = Array.isArray(group.account_emails)
                    ? group.account_emails.indexOf(String(email).toLowerCase())
                    : -1;
                if (position < 0) {
                    throw new Error(`${groupId}/${threshold} ödül kodu gruba ait olmayan hesap içeriyor.`);
                }
                records.push({
                    groupId,
                    sequence: Number(group.sequence) || Number.MAX_SAFE_INTEGER,
                    position,
                    threshold: Number(threshold),
                    line: collectedCodeLine(email, Number(threshold), code),
                });
            }
        }
    }
    records.sort((left, right) =>
        left.sequence - right.sequence ||
        left.threshold - right.threshold ||
        left.position - right.position ||
        left.groupId.localeCompare(right.groupId),
    );

    const desiredLines = records.map((record) => record.line);
    const desired = desiredLines.length ? `${desiredLines.join('\n')}\n` : '';
    const existing = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf8') : '';
    const existingLines = existing.split(/\r?\n/).filter(Boolean);
    const desiredSet = new Set(desiredLines);
    const existingSet = new Set(existingLines);
    const stats = {
        changed: existing !== desired,
        total: desiredLines.length,
        addedLines: desiredLines.filter((line) => !existingSet.has(line)).length,
        removedStaleLines: existingLines.filter((line) => !desiredSet.has(line)).length,
    };
    if (stats.changed) {
        writeCollectedCodesAtomically(targetPath, desired);
    }
    return stats;
}

function eligibleMilestones(signCount, claimedRewards) {
    const claimed = new Set((claimedRewards || []).map(Number));
    return REWARD_MILESTONES.filter(
        (milestone) => Number(signCount) >= milestone.threshold && !claimed.has(milestone.threshold),
    );
}

async function runRewardPackage(group, callbacks = {}, dependencies = {}) {
    if (!group || !Array.isArray(group.accounts) || group.accounts.length !== 4) {
        throw new Error('Reward paketi tam olarak dört hesap içermelidir.');
    }
    const emails = group.accounts.map((account) => String(account.email || '').trim().toLowerCase());
    if (emails.some((email) => !email) || new Set(emails).size !== 4) {
        throw new Error('Reward paketindeki dört hesap dolu ve benzersiz olmalıdır.');
    }

    const browserLauncher = dependencies.launchBrowser || launchBrowser;
    const accountLogin = dependencies.login || login;
    const eventSessionOpener = dependencies.openVerifiedEventSession || openVerifiedEventSession;
    const eventRegistrationEnsurer = dependencies.ensureRewardEventRegistration ||
        ensureRewardEventRegistration;
    const rewardClaimer = dependencies.claimRewardMilestone || claimRewardMilestone;
    const credentialResolver = dependencies.passwordForEmail || passwordForEmail;
    const signConfirmer = dependencies.confirmSign || confirmSign;

    let newlySignedCount = 0;
    const claimed = [];
    let runningSignCount = Number(group.signCount || 4);
    const alreadySigned = new Set((group.rewardSignedAccounts || []).map((e) => String(e).toLowerCase()));
    const claimedRewardsSet = new Set((group.claimedRewards || []).map(Number));

    const codeAlreadyStored = (email, threshold) => {
        const stored = group.rewardCodes && group.rewardCodes[threshold];
        if (typeof stored === 'string') {
            return email === emails[0] && Boolean(stored.trim());
        }
        return Boolean(stored && typeof stored === 'object' && String(stored[email] || '').trim());
    };

    const browser = await browserLauncher();
    try {
        // === PASS 1: İMZA (Sadece gerekiyorsa giriş yap) ===
        if (group.needsResign) {
            for (let index = 0; index < group.accounts.length; index += 1) {
                const account = group.accounts[index];
                const accountEmail = String(account.email).trim().toLowerCase();

                if (alreadySigned.has(accountEmail)) {
                    console.log(`[BOT 4] [${accountEmail}] zaten imzalı (atlandı).`);
                    continue; // GİRİŞ YAPMA, ZATEN İMZALI
                }

                let accountCompleted = false;
                let lastError = null;

                for (let sessionAttempt = 1; sessionAttempt <= 2; sessionAttempt += 1) {
                    const context = await browser.createBrowserContext();
                    try {
                        const page = await context.newPage();
                        await accountLogin(page, accountEmail, credentialResolver(accountEmail));
                        
                        const signResult = await signConfirmer(page, accountEmail);
                        newlySignedCount += 1;
                        runningSignCount += 1;
                        alreadySigned.add(accountEmail);
                        
                        const signType = signResult.first === 'already_signed' ? 'zaten imzalı' : 'yeni imza';
                        console.log(`[BOT 4] [${accountEmail}] ${signType} (sign_count: ${runningSignCount}).`);
                        
                        if (typeof callbacks.onAccountSigned === 'function') {
                            await callbacks.onAccountSigned(accountEmail, signResult);
                        }
                        accountCompleted = true;
                        break;
                    } catch (error) {
                        lastError = error;
                        if (!isRecoverableBrowserSessionError(error) || sessionAttempt >= 2) {
                            throw error;
                        }
                        console.warn(`[BOT 4] ${accountEmail} imza hatası (deneme ${sessionAttempt}/2): ${error.message}. Yeniden deneniyor...`);
                        await context.close().catch(() => {});
                    } finally {
                        if (accountCompleted) {
                            await context.close().catch(() => {});
                        }
                    }
                }
            }
        }

        // === PASS 2: ÖDÜL TOPLAMA (Sadece alınacak ödül varsa giriş yap) ===
        const milestones = eligibleMilestones(runningSignCount, [...claimedRewardsSet]);
        if (milestones.length > 0) {
            for (let index = 0; index < group.accounts.length; index += 1) {
                const account = group.accounts[index];
                const accountEmail = String(account.email).trim().toLowerCase();

                const pendingMilestones = milestones.filter(
                    (milestone) => !codeAlreadyStored(accountEmail, milestone.threshold),
                );

                if (pendingMilestones.length === 0) {
                    continue; // GİRİŞ YAPMA, ALINACAK KOD YOK
                }

                let accountCompleted = false;
                let lastError = null;

                for (let sessionAttempt = 1; sessionAttempt <= 2; sessionAttempt += 1) {
                    const context = await browser.createBrowserContext();
                    const claimedBeforeAttempt = claimed.length;
                    try {
                        const page = await context.newPage();
                        await accountLogin(page, accountEmail, credentialResolver(accountEmail));
                        
                        let session = await eventSessionOpener(page, accountEmail);
                        session = await eventRegistrationEnsurer(page, accountEmail, session, account);
                        
                        for (const milestone of pendingMilestones) {
                            const result = await rewardClaimer(page, accountEmail, session, milestone);
                            const record = {
                                email: accountEmail,
                                threshold: milestone.threshold,
                                level: milestone.level,
                                code: result.code,
                                reconciled: result.reconciled,
                            };
                            claimed.push(record);
                            claimedRewardsSet.add(milestone.threshold);
                            if (typeof callbacks.onRewardClaimed === 'function') {
                                await callbacks.onRewardClaimed(accountEmail, milestone.threshold, result.code, result);
                            }
                        }
                        accountCompleted = true;
                        break;
                    } catch (error) {
                        lastError = error;
                        if (!isRecoverableBrowserSessionError(error) || sessionAttempt >= 2 || claimed.length > claimedBeforeAttempt) {
                            throw error;
                        }
                        console.warn(`[BOT 4] ${accountEmail} ödül toplama hatası (deneme ${sessionAttempt}/2): ${error.message}. Yeniden deneniyor...`);
                        await context.close().catch(() => {});
                    } finally {
                        if (accountCompleted) {
                            await context.close().catch(() => {});
                        }
                    }
                }
                
                if (!accountCompleted) {
                    throw lastError || new Error(`${accountEmail} reward oturumu kurulamadı.`);
                }

                // Hesaplar arası kısa bekleme (CloudFront koruma)
                if (index < group.accounts.length - 1) {
                    await new Promise(r => setTimeout(r, 15000));
                }
            }
        }
        
    } finally {
        await browser.close().catch(() => {});
    }
    
    return { newlySignedCount, claimed };
}

module.exports = {
    applyRuntimeTiming,
    appendCollectedCode,
    claimRewardMilestone,
    eligibleMilestones,
    ensureRewardEventRegistration,
    existingRewardObservations,
    fetchTeamCodes,
    getActivityApi,
    normalizeTeamCodes,
    postActivityApi,
    rewardCodeForMilestone,
    runRewardPackage,
    selectRewardRegistrationRole,
    synchronizeCollectedCodes,
};
